//! Concrete integer data types — every Apache Arrow signed and unsigned integer.
//!
//! One module per type (`int8`, …, `uint64`), each with one file per concern:
//! `data_type.rs`, `field.rs` and `scalar.rs`. The three share the same shape (a
//! little-endian byte codec, a nullable field, a possibly-null scalar), so each is
//! generated by a focused crate-internal macro — [`int_data_type!`], [`int_field!`]
//! and [`int_scalar!`] — keeping every per-type file a single invocation while the
//! logic lives in one place.

/// Generates a fixed-width integer data type `$ty` (native Rust `$native`), with
/// `$name` its lowercase name, `$format` its Arrow C Data Interface format string and
/// `$width` its byte width. The `$ty` identifier doubles as the matching
/// [`DataTypeId`](crate::DataTypeId) variant (exposed as `$ty::ID`) and the matching
/// [`arrow_schema::DataType`] variant (`to_arrow` / `from_arrow`).
macro_rules! int_data_type {
    ($ty:ident, $native:ty, $name:literal, $format:literal, $width:literal) => {
        #[doc = concat!("The Apache Arrow `", $name, "` data type: a fixed-width integer primitive (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $ty;

        impl $ty {
            /// This type's [`DataTypeId`](crate::DataTypeId).
            pub const ID: $crate::DataTypeId = $crate::DataTypeId::$ty;
        }

        impl $crate::RawDataType for $ty {
            fn name(&self) -> &str {
                $name
            }
            fn arrow_format(&self) -> String {
                $format.to_string()
            }
            fn byte_width(&self) -> Option<usize> {
                Some($width)
            }
            fn to_arrow(&self) -> $crate::arrow_schema::DataType {
                $crate::arrow_schema::DataType::$ty
            }
            fn from_arrow(
                data_type: &$crate::arrow_schema::DataType,
            ) -> Result<Self, $crate::DataError> {
                match data_type {
                    $crate::arrow_schema::DataType::$ty => Ok(Self),
                    other => Err($crate::DataError::IncompatibleArrowType {
                        expected: stringify!($ty).to_string(),
                        got: other.to_string(),
                    }),
                }
            }
        }

        impl $crate::DataType<$native> for $ty {
            fn native_to_bytes(&self, value: &$native) -> Vec<u8> {
                value.to_le_bytes().to_vec()
            }
            fn native_from_bytes(&self, bytes: &[u8]) -> Result<$native, $crate::DataError> {
                let array: [u8; $width] =
                    bytes
                        .try_into()
                        .map_err(|_| $crate::DataError::InvalidByteLength {
                            expected: $width,
                            got: bytes.len(),
                        })?;
                Ok(<$native>::from_le_bytes(array))
            }
        }

        impl $crate::Primitive for $ty {}
    };
}
pub(crate) use int_data_type;

/// Generates a nullable field `$field` for the integer data type `$ty` (native
/// `$native`), with `$name` used in its documentation.
macro_rules! int_field {
    ($field:ident, $ty:ty, $native:ty, $name:literal) => {
        #[doc = concat!("A nullable `", $name, "` field: a name paired with the ", stringify!($ty), " data type.")]
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $field {
            name: String,
            data_type: $ty,
            nullable: bool,
        }

        impl $field {
            #[doc = concat!("A `", $name, "` field named `name`.")]
            pub fn new(name: impl Into<String>, nullable: bool) -> Self {
                Self {
                    name: name.into(),
                    data_type: <$ty as ::core::default::Default>::default(),
                    nullable,
                }
            }
        }

        impl $crate::RawField<$ty> for $field {
            fn name(&self) -> &str {
                &self.name
            }
            fn data_type(&self) -> &$ty {
                &self.data_type
            }
            fn is_nullable(&self) -> bool {
                self.nullable
            }
            fn from_arrow(
                field: &$crate::arrow_schema::Field,
            ) -> Result<Self, $crate::DataError> {
                <$ty as $crate::RawDataType>::from_arrow(field.data_type())?;
                $crate::raw_field::validate_field_metadata(field, stringify!($ty))?;
                Ok(Self::new(field.name(), field.is_nullable()))
            }
        }

        impl $crate::Field<$native> for $field {
            type Type = $ty;
        }
    };
}
pub(crate) use int_field;

/// Generates a single, possibly-null scalar `$scalar` for the integer data type `$ty`
/// (native `$native`), with `$name` used in its documentation and `$array` the
/// matching [`arrow_array`] primitive array (`to_arrow` / `from_arrow`). The scalar
/// also converts from its native value: `From<$native>` and `From<Option<$native>>`
/// (where `None` is the null scalar).
macro_rules! int_scalar {
    ($scalar:ident, $ty:ty, $native:ty, $name:literal, $array:ident) => {
        #[doc = concat!("A single, possibly-null `", $name, "` value (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $scalar {
            data_type: $ty,
            value: Option<$native>,
        }

        impl $scalar {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            pub fn new(value: $native) -> Self {
                Self {
                    data_type: <$ty as ::core::default::Default>::default(),
                    value: Some(value),
                }
            }

            #[doc = concat!("A null `", $name, "` scalar.")]
            pub fn null() -> Self {
                Self {
                    data_type: <$ty as ::core::default::Default>::default(),
                    value: None,
                }
            }
        }

        // `try_into` is an identity conversion for the scalar's own width (e.g.
        // `as_i64` on an int64), which clippy would flag; the macro generates all
        // ten numeric targets uniformly, so allow it once here.
        #[allow(clippy::useless_conversion)]
        impl $crate::RawScalar<$ty> for $scalar {
            type Value = $native;
            fn data_type(&self) -> &$ty {
                &self.data_type
            }
            fn is_null(&self) -> bool {
                self.value.is_none()
            }
            fn value(&self) -> Option<&$native> {
                self.value.as_ref()
            }
            fn to_arrow(&self) -> $crate::arrow_array::ArrayRef {
                match self.value {
                    // One element, no null buffer — cheaper than building through
                    // `Vec<Option<_>>`.
                    Some(value) => {
                        ::std::sync::Arc::new($crate::arrow_array::$array::from_iter_values(
                            [value],
                        ))
                    }
                    // Arrow arrays are immutable, so every null scalar shares one
                    // cached one-null array; a clone is a reference-count bump
                    // instead of two buffer allocations.
                    None => {
                        static NULL: ::std::sync::OnceLock<$crate::arrow_array::ArrayRef> =
                            ::std::sync::OnceLock::new();
                        NULL.get_or_init(|| {
                            ::std::sync::Arc::new($crate::arrow_array::$array::new_null(1))
                        })
                        .clone()
                    }
                }
            }
            fn from_arrow(
                array: &dyn $crate::arrow_array::Array,
            ) -> Result<Self, $crate::DataError> {
                // Fully-qualified `Array` calls: the trait is not in scope at the
                // macro's expansion site.
                let length = $crate::arrow_array::Array::len(array);
                if length != 1 {
                    return Err($crate::DataError::InvalidScalarLength { got: length });
                }
                let array = array
                    .as_any()
                    .downcast_ref::<$crate::arrow_array::$array>()
                    .ok_or_else(|| $crate::DataError::IncompatibleArrowType {
                        expected: stringify!($ty).to_string(),
                        got: $crate::arrow_array::Array::data_type(array).to_string(),
                    })?;
                Ok(if $crate::arrow_array::Array::is_null(array, 0) {
                    Self::null()
                } else {
                    Self::new(array.value(0))
                })
            }
            fn as_i8(&self) -> Option<i8> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_i16(&self) -> Option<i16> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_i32(&self) -> Option<i32> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_i64(&self) -> Option<i64> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_u8(&self) -> Option<u8> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_u16(&self) -> Option<u16> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_u32(&self) -> Option<u32> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_u64(&self) -> Option<u64> {
                self.value.and_then(|value| value.try_into().ok())
            }
            fn as_f32(&self) -> Option<f32> {
                // Exactly representable only: an int-to-float cast rounds to an
                // integral float, so a lossless conversion round-trips through i128.
                self.value.and_then(|value| {
                    let float = value as f32;
                    (float as i128 == value as i128).then_some(float)
                })
            }
            fn as_f64(&self) -> Option<f64> {
                self.value.and_then(|value| {
                    let float = value as f64;
                    (float as i128 == value as i128).then_some(float)
                })
            }
        }

        impl $crate::Scalar<$native> for $scalar {
            type Type = $ty;
        }

        impl ::core::convert::From<$native> for $scalar {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            fn from(value: $native) -> Self {
                Self::new(value)
            }
        }

        impl ::core::convert::From<::core::option::Option<$native>> for $scalar {
            #[doc = concat!("A `", $name, "` scalar holding `value`, or the null scalar for `None`.")]
            fn from(value: ::core::option::Option<$native>) -> Self {
                match value {
                    ::core::option::Option::Some(value) => Self::new(value),
                    ::core::option::Option::None => Self::null(),
                }
            }
        }
    };
}
pub(crate) use int_scalar;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::{Int16, Int16Field, Int16Scalar};
pub use int32::{Int32, Int32Field, Int32Scalar};
pub use int64::{Int64, Int64Field, Int64Scalar};
pub use int8::{Int8, Int8Field, Int8Scalar};
pub use uint16::{UInt16, UInt16Field, UInt16Scalar};
pub use uint32::{UInt32, UInt32Field, UInt32Scalar};
pub use uint64::{UInt64, UInt64Field, UInt64Scalar};
pub use uint8::{UInt8, UInt8Field, UInt8Scalar};
