//! Concrete integer data types — every Apache Arrow signed and unsigned integer.
//!
//! One module per type (`int8`, …, `uint64`), each with one file per concern:
//! `data_type.rs`, `field.rs` and `scalar.rs`. The three share the same shape (a
//! little-endian byte codec, a nullable field, a possibly-null scalar), so each is
//! generated by a focused crate-internal macro — [`int_data_type!`], [`int_field!`]
//! and [`int_scalar!`] — keeping every per-type file a single invocation while the
//! logic lives in one place.

/// Generates a fixed-width integer data type `$ty` (native Rust `$native`), with
/// `$name` its lowercase name, `$format` its Arrow C Data Interface format string and
/// `$width` its byte width. The `$ty` identifier doubles as the matching
/// [`DataTypeId`](crate::DataTypeId) variant, exposed as `$ty::ID`.
macro_rules! int_data_type {
    ($ty:ident, $native:ty, $name:literal, $format:literal, $width:literal) => {
        #[doc = concat!("The Apache Arrow `", $name, "` data type: a fixed-width integer primitive (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $ty;

        impl $ty {
            /// This type's [`DataTypeId`](crate::DataTypeId).
            pub const ID: $crate::DataTypeId = $crate::DataTypeId::$ty;
        }

        impl $crate::RawDataType for $ty {
            fn name(&self) -> &str {
                $name
            }
            fn arrow_format(&self) -> String {
                $format.to_string()
            }
            fn byte_width(&self) -> Option<usize> {
                Some($width)
            }
        }

        impl $crate::DataType<$native> for $ty {
            fn native_to_bytes(&self, value: &$native) -> Vec<u8> {
                value.to_le_bytes().to_vec()
            }
            fn native_from_bytes(&self, bytes: &[u8]) -> Result<$native, $crate::DataError> {
                let array: [u8; $width] =
                    bytes
                        .try_into()
                        .map_err(|_| $crate::DataError::InvalidByteLength {
                            expected: $width,
                            got: bytes.len(),
                        })?;
                Ok(<$native>::from_le_bytes(array))
            }
        }

        impl $crate::Primitive for $ty {}
    };
}
pub(crate) use int_data_type;

/// Generates a nullable field `$field` for the integer data type `$ty` (native
/// `$native`), with `$name` used in its documentation.
macro_rules! int_field {
    ($field:ident, $ty:ty, $native:ty, $name:literal) => {
        #[doc = concat!("A nullable `", $name, "` field: a name paired with the ", stringify!($ty), " data type.")]
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $field {
            name: String,
            data_type: $ty,
            nullable: bool,
        }

        impl $field {
            #[doc = concat!("A `", $name, "` field named `name`.")]
            pub fn new(name: impl Into<String>, nullable: bool) -> Self {
                Self {
                    name: name.into(),
                    data_type: <$ty as ::core::default::Default>::default(),
                    nullable,
                }
            }
        }

        impl $crate::RawField<$ty> for $field {
            fn name(&self) -> &str {
                &self.name
            }
            fn data_type(&self) -> &$ty {
                &self.data_type
            }
            fn is_nullable(&self) -> bool {
                self.nullable
            }
        }

        impl $crate::Field<$native> for $field {
            type Type = $ty;
        }
    };
}
pub(crate) use int_field;

/// Generates a single, possibly-null scalar `$scalar` for the integer data type `$ty`
/// (native `$native`), with `$name` used in its documentation.
macro_rules! int_scalar {
    ($scalar:ident, $ty:ty, $native:ty, $name:literal) => {
        #[doc = concat!("A single, possibly-null `", $name, "` value (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $scalar {
            data_type: $ty,
            value: Option<$native>,
        }

        impl $scalar {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            pub fn new(value: $native) -> Self {
                Self {
                    data_type: <$ty as ::core::default::Default>::default(),
                    value: Some(value),
                }
            }

            #[doc = concat!("A null `", $name, "` scalar.")]
            pub fn null() -> Self {
                Self {
                    data_type: <$ty as ::core::default::Default>::default(),
                    value: None,
                }
            }
        }

        impl $crate::RawScalar<$ty> for $scalar {
            type Value = $native;
            fn data_type(&self) -> &$ty {
                &self.data_type
            }
            fn is_null(&self) -> bool {
                self.value.is_none()
            }
            fn value(&self) -> Option<&$native> {
                self.value.as_ref()
            }
        }

        impl $crate::Scalar<$native> for $scalar {
            type Type = $ty;
        }
    };
}
pub(crate) use int_scalar;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::{Int16, Int16Field, Int16Scalar};
pub use int32::{Int32, Int32Field, Int32Scalar};
pub use int64::{Int64, Int64Field, Int64Scalar};
pub use int8::{Int8, Int8Field, Int8Scalar};
pub use uint16::{UInt16, UInt16Field, UInt16Scalar};
pub use uint32::{UInt32, UInt32Field, UInt32Scalar};
pub use uint64::{UInt64, UInt64Field, UInt64Scalar};
pub use uint8::{UInt8, UInt8Field, UInt8Scalar};
