//! Concrete integer scalars — every Apache Arrow signed and unsigned integer.
//!
//! One file per type (`int8.rs`, …, `uint64.rs`), mirroring `yggdryl-dtype`'s
//! [`integer`](yggdryl_dtype::integer) module. The eight scalars share the same
//! shape (a possibly-null native value with exact-or-error `as_*` accessors), so
//! each is generated by the focused crate-internal [`int_scalar!`] macro — keeping
//! every per-type file a single invocation while the logic lives in one place. The
//! macro also wires the [`ScalarFactory`](crate::ScalarFactory) so the data type
//! builds its scalar (`Int64Type.scalar(42)`).

/// Generates a single, possibly-null scalar `$ty` (e.g. `Int64Scalar`) over the
/// `yggdryl-dtype` data type `$dtype` (e.g. `Int64Type`, native `$native`), with
/// `$name` used in its documentation and `$array` the matching [`arrow_array`]
/// primitive array (`to_arrow` / `from_arrow`). The scalar also converts from its
/// native value — `From<$native>` and `From<Option<$native>>` (where `None` is the
/// null scalar) — and the data type gains its [`ScalarFactory`](crate::ScalarFactory)
/// impl.
macro_rules! int_scalar {
    ($ty:ident, $dtype:ident, $native:ty, $name:literal, $array:ident) => {
        #[doc = concat!("A single, possibly-null `", $name, "` value (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $ty {
            data_type: ::yggdryl_dtype::$dtype,
            value: Option<$native>,
        }

        impl $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            pub fn new(value: $native) -> Self {
                Self {
                    data_type: ::yggdryl_dtype::$dtype,
                    value: Some(value),
                }
            }

            #[doc = concat!("A null `", $name, "` scalar.")]
            pub fn null() -> Self {
                Self {
                    data_type: ::yggdryl_dtype::$dtype,
                    value: None,
                }
            }
        }

        // `try_into` is an identity conversion for the scalar's own width (e.g.
        // `as_i64` on an int64), which clippy would flag; the macro generates all
        // ten numeric targets uniformly, so allow it once here.
        #[allow(clippy::useless_conversion)]
        impl $crate::Scalar<::yggdryl_dtype::$dtype> for $ty {
            type Value = $native;
            fn data_type(&self) -> &::yggdryl_dtype::$dtype {
                &self.data_type
            }
            fn is_null(&self) -> bool {
                self.value.is_none()
            }
            fn value(&self) -> Option<&$native> {
                self.value.as_ref()
            }
            fn to_arrow(&self) -> $crate::arrow_array::ArrayRef {
                match self.value {
                    // One element, no null buffer — cheaper than building through
                    // `Vec<Option<_>>`.
                    Some(value) => {
                        ::std::sync::Arc::new($crate::arrow_array::$array::from_iter_values(
                            [value],
                        ))
                    }
                    // Arrow arrays are immutable, so every null scalar shares one
                    // cached one-null array; a clone is a reference-count bump
                    // instead of two buffer allocations.
                    None => {
                        static NULL: ::std::sync::OnceLock<$crate::arrow_array::ArrayRef> =
                            ::std::sync::OnceLock::new();
                        NULL.get_or_init(|| {
                            ::std::sync::Arc::new($crate::arrow_array::$array::new_null(1))
                        })
                        .clone()
                    }
                }
            }
            fn from_arrow(
                array: &dyn $crate::arrow_array::Array,
            ) -> Result<Self, ::yggdryl_dtype::DataError> {
                // Fully-qualified `Array` calls: the trait is not in scope at the
                // macro's expansion site.
                let length = $crate::arrow_array::Array::len(array);
                if length != 1 {
                    return Err(::yggdryl_dtype::DataError::InvalidScalarLength { got: length });
                }
                let array = array
                    .as_any()
                    .downcast_ref::<$crate::arrow_array::$array>()
                    .ok_or_else(|| ::yggdryl_dtype::DataError::IncompatibleArrowType {
                        expected: stringify!($dtype).to_string(),
                        got: $crate::arrow_array::Array::data_type(array).to_string(),
                    })?;
                Ok(if $crate::arrow_array::Array::is_null(array, 0) {
                    Self::null()
                } else {
                    Self::new(array.value(0))
                })
            }
            fn as_i8(&self) -> Result<i8, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "i8",
                    })
            }
            fn as_i16(&self) -> Result<i16, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "i16",
                    })
            }
            fn as_i32(&self) -> Result<i32, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "i32",
                    })
            }
            fn as_i64(&self) -> Result<i64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "i64",
                    })
            }
            fn as_u8(&self) -> Result<u8, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "u8",
                    })
            }
            fn as_u16(&self) -> Result<u16, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "u16",
                    })
            }
            fn as_u32(&self) -> Result<u32, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "u32",
                    })
            }
            fn as_u64(&self) -> Result<u64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                value
                    .try_into()
                    .map_err(|_| ::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "u64",
                    })
            }
            fn as_f32(&self) -> Result<f32, ::yggdryl_dtype::DataError> {
                // Exactly representable only: an int-to-float cast rounds to an
                // integral float, so a lossless conversion round-trips through i128.
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                let float = value as f32;
                if float as i128 == value as i128 {
                    Ok(float)
                } else {
                    Err(::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "f32",
                    })
                }
            }
            fn as_f64(&self) -> Result<f64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                let float = value as f64;
                if float as i128 == value as i128 {
                    Ok(float)
                } else {
                    Err(::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "f64",
                    })
                }
            }
        }

        impl $crate::TypedScalar<::yggdryl_dtype::$dtype, $native> for $ty {}

        impl $crate::ScalarFactory<$native> for ::yggdryl_dtype::$dtype {
            type Scalar = $ty;
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            fn scalar(&self, value: $native) -> $ty {
                $ty::new(value)
            }
            #[doc = concat!("The null `", $name, "` scalar.")]
            fn null_scalar(&self) -> $ty {
                $ty::null()
            }
            #[doc = concat!("The default `", $name, "` scalar: a scalar holding `0`.")]
            fn default_scalar(&self) -> $ty {
                $ty::new(<$native>::default())
            }
        }

        impl ::core::convert::From<$native> for $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            fn from(value: $native) -> Self {
                Self::new(value)
            }
        }

        impl ::core::convert::From<::core::option::Option<$native>> for $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`, or the null scalar for `None`.")]
            fn from(value: ::core::option::Option<$native>) -> Self {
                match value {
                    ::core::option::Option::Some(value) => Self::new(value),
                    ::core::option::Option::None => Self::null(),
                }
            }
        }
    };
}
pub(crate) use int_scalar;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::Int16Scalar;
pub use int32::Int32Scalar;
pub use int64::Int64Scalar;
pub use int8::Int8Scalar;
pub use uint16::UInt16Scalar;
pub use uint32::UInt32Scalar;
pub use uint64::UInt64Scalar;
pub use uint8::UInt8Scalar;
