//! The well-known MIME and filename-extension registry.

use super::MimeType;

macro_rules! known_mimes {
    ($value:expr, $(($mime:literal, $constant:ident)),+ $(,)?) => {{
        $(if $value.eq_ignore_ascii_case($mime) {
            return Some(MimeType::$constant);
        })+
        None
    }};
}

pub(super) fn known_from_mime(value: &str) -> Option<MimeType> {
    known_mimes!(
        value,
        ("application/octet-stream", OCTET_STREAM),
        ("inode/directory", DIRECTORY),
        ("inode/file", FILE),
        ("application/json", JSON),
        ("application/x-ndjson", JSON_LINES),
        ("application/ndjson", JSON_LINES),
        ("application/jsonl", JSON_LINES),
        ("application/yaml", YAML),
        ("application/x-yaml", YAML),
        ("text/yaml", YAML),
        ("application/toml", TOML),
        ("text/csv", CSV),
        ("text/tab-separated-values", TSV),
        ("application/vnd.apache.parquet", PARQUET),
        ("application/vnd.apache.arrow.file", ARROW_FILE),
        ("application/vnd.apache.arrow.stream", ARROW_STREAM),
        ("application/avro", AVRO),
        ("application/vnd.apache.avro", AVRO),
        ("application/vnd.apache.orc", ORC),
        ("application/vnd.apache.puffin", PUFFIN),
        ("text/plain", PLAIN_TEXT),
        ("text/markdown", MARKDOWN),
        ("text/html", HTML),
        ("text/css", CSS),
        ("text/javascript", JAVASCRIPT),
        ("application/javascript", JAVASCRIPT),
        ("application/xml", XML),
        ("text/xml", XML),
        ("application/pdf", PDF),
        ("application/cbor", CBOR),
        ("application/vnd.msgpack", MESSAGE_PACK),
        ("application/msgpack", MESSAGE_PACK),
        ("application/protobuf", PROTOBUF),
        ("application/x-protobuf", PROTOBUF),
        ("application/vnd.sqlite3", SQLITE3),
        ("image/png", PNG),
        ("image/jpeg", JPEG),
        ("image/gif", GIF),
        ("image/webp", WEBP),
        ("image/svg+xml", SVG),
        ("audio/mpeg", MP3),
        ("audio/wav", WAV),
        ("audio/x-wav", WAV),
        ("audio/ogg", OGG),
        ("audio/flac", FLAC),
        ("video/mp4", MP4),
        ("video/webm", WEBM),
        ("font/woff", WOFF),
        ("font/woff2", WOFF2),
        ("font/ttf", TTF),
        ("font/otf", OTF),
        ("application/vnd.ms-excel", XLS),
        (
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            XLSX
        ),
        ("application/vnd.oasis.opendocument.spreadsheet", ODS),
        ("application/msword", DOC),
        (
            "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
            DOCX
        ),
        ("application/gzip", GZIP),
        ("application/x-gzip", GZIP),
        ("application/zstd", ZSTD),
        ("application/x-brotli", BROTLI),
        ("application/zlib", ZLIB),
        ("application/x-compress", COMPRESS),
        ("application/x-bzip2", BZIP2),
        ("application/x-xz", XZ),
        ("application/x-lz4", LZ4),
        ("application/x-snappy-framed", SNAPPY),
        ("application/zip", ZIP),
        ("application/x-7z-compressed", SEVEN_ZIP),
        ("application/vnd.rar", RAR),
        ("application/x-rar-compressed", RAR),
        ("application/x-tar", TAR),
    )
}

macro_rules! known_extensions {
    ($value:expr, $(($extension:literal, $constant:ident)),+ $(,)?) => {{
        $(if $value.eq_ignore_ascii_case($extension) {
            return Some(MimeType::$constant);
        })+
        None
    }};
}

pub(super) fn known_from_extension(value: &str) -> Option<MimeType> {
    known_extensions!(
        value,
        ("bin", OCTET_STREAM),
        ("json", JSON),
        ("jsonl", JSON_LINES),
        ("ndjson", JSON_LINES),
        ("yaml", YAML),
        ("yml", YAML),
        ("toml", TOML),
        ("csv", CSV),
        ("tsv", TSV),
        ("tab", TSV),
        ("parquet", PARQUET),
        ("pq", PARQUET),
        ("arrow", ARROW_FILE),
        ("feather", ARROW_FILE),
        ("ipc", ARROW_FILE),
        ("arrows", ARROW_STREAM),
        ("avro", AVRO),
        ("orc", ORC),
        ("puffin", PUFFIN),
        ("txt", PLAIN_TEXT),
        ("text", PLAIN_TEXT),
        ("log", PLAIN_TEXT),
        ("md", MARKDOWN),
        ("markdown", MARKDOWN),
        ("html", HTML),
        ("htm", HTML),
        ("css", CSS),
        ("js", JAVASCRIPT),
        ("mjs", JAVASCRIPT),
        ("cjs", JAVASCRIPT),
        ("xml", XML),
        ("pdf", PDF),
        ("cbor", CBOR),
        ("msgpack", MESSAGE_PACK),
        ("mpk", MESSAGE_PACK),
        ("pb", PROTOBUF),
        ("protobuf", PROTOBUF),
        ("sqlite", SQLITE3),
        ("sqlite3", SQLITE3),
        ("db", SQLITE3),
        ("png", PNG),
        ("jpg", JPEG),
        ("jpeg", JPEG),
        ("jpe", JPEG),
        ("gif", GIF),
        ("webp", WEBP),
        ("svg", SVG),
        ("mp3", MP3),
        ("wav", WAV),
        ("wave", WAV),
        ("ogg", OGG),
        ("oga", OGG),
        ("flac", FLAC),
        ("mp4", MP4),
        ("m4v", MP4),
        ("webm", WEBM),
        ("woff", WOFF),
        ("woff2", WOFF2),
        ("ttf", TTF),
        ("otf", OTF),
        ("xls", XLS),
        ("xlsx", XLSX),
        ("ods", ODS),
        ("doc", DOC),
        ("docx", DOCX),
        ("gz", GZIP),
        ("gzip", GZIP),
        ("zst", ZSTD),
        ("zstd", ZSTD),
        ("br", BROTLI),
        ("zz", ZLIB),
        ("zlib", ZLIB),
        ("Z", COMPRESS),
        ("bz2", BZIP2),
        ("bzip2", BZIP2),
        ("xz", XZ),
        ("lz4", LZ4),
        ("snappy", SNAPPY),
        ("sz", SNAPPY),
        ("zip", ZIP),
        ("7z", SEVEN_ZIP),
        ("rar", RAR),
        ("tar", TAR),
    )
}
