//! Market data over the yggdryl core: the four market enum kinds a column
//! declares - [`MarketDataKind`], [`MarketDataType`], [`Side`] and
//! [`TimeInForce`] - each claimed on the core's register by [`install`]; the
//! identifiers an element states ([`IdKey`], [`Identifier`],
//! [`Identifiers`], [`IdType`], [`IdSource`]); the instrument registry
//! ([`IsinRegistry`]); a book's price level ([`Limit`]); a structured
//! product's category ([`Eusipa`]); and [`graph`], the market leaves, the
//! walk over them, the books and their Arrow rows, beside the event
//! vocabulary the core's `yggdryl::graph` keeps.

#![deny(unsafe_code)]

mod eusipa;
pub mod identifier;
mod idkey;
mod idsource;
mod idtype;
mod isin_registry;
pub mod limit;
pub mod marketdatakind;
pub mod marketdatatype;
pub mod securityid;
pub mod side;
pub mod timeinforce;
pub use eusipa::Eusipa;
pub use identifier::{IdWord, Identifier, Identifiers};
pub use idkey::IdKey;
pub use idsource::IdSource;
pub use idtype::IdType;
pub use isin_registry::{IsinEntry, IsinRegistry, MatchTier, Resolution, Unmatched};
pub use limit::Limit;
pub use marketdatakind::*;
pub use marketdatatype::*;
pub use side::*;
pub use timeinforce::*;
pub mod graph;
#[doc(hidden)]
pub mod implementer;

/// What this crate claims its kinds as.
const CRATE: &str = "yggdryl-market";

/// The listings this crate's kinds prebuild for a text column declaring
/// their codes, by the logical name that spells each.
const PREBUILT: [(&str, &[&str]); 2] = [("side", SIDES), ("timeinforce", TIMESINFORCE)];

/// The kinds this crate claims, in byte order.
const KINDS: [&yggdryl::MarketDescriptor; 4] = [
    &MARKETDATAKIND_KIND,
    &SIDE_KIND,
    &MARKETDATATYPE_KIND,
    &TIMEINFORCE_KIND,
];

/// Claims the four market kinds on the core's register - each one's byte,
/// name and Arrow extension name - and registers the `side` and
/// `timeinforce` listings ([`SIDES`], [`TIMESINFORCE`]) a text column of
/// their codes prebuilds, once for the life of the process; a later call
/// returns at once. Every binding's init and the CLI's `main`
/// call it, and so does a Rust caller before the core reads a market name:
/// a parsed `side`, a serde tag, a value-stream byte or a `yggdryl.side`
/// extension name is refused until the kind is claimed.
///
/// # Errors
///
/// Returns the register's refusal where another crate claimed one of these
/// bytes, names or extension names first.
pub fn install() -> yggdryl::Result<()> {
    static INSTALLED: std::sync::OnceLock<()> = std::sync::OnceLock::new();
    static INSTALLING: std::sync::Mutex<()> = std::sync::Mutex::new(());
    if INSTALLED.get().is_some() {
        return Ok(());
    }
    let _installing = INSTALLING
        .lock()
        .unwrap_or_else(std::sync::PoisonError::into_inner);
    if INSTALLED.get().is_some() {
        return Ok(());
    }
    for kind in KINDS {
        if yggdryl::market::kind_of(kind.id).is_some_and(|held| std::ptr::eq(held, kind)) {
            continue;
        }
        yggdryl::market::claim(kind, CRATE)?;
    }
    for (name, values) in PREBUILT {
        // A `const` listing has no one address, so the held one is compared
        // by its values.
        if yggdryl::StringEnum::prebuilt_values(name) == values {
            continue;
        }
        yggdryl::StringEnum::register_prebuilt(name, values, CRATE)?;
    }
    let _ = INSTALLED.set(());
    Ok(())
}

// GENERATED by scripts/generate_internals.py - do not edit by hand.
/// What the test suite pins and a caller cannot reach.
///
/// Every test lives in `rust/market/tests/` and reaches the crate through
/// `yggdryl_market::`. The handful that pin something no caller can name reach it
/// here instead, under a feature no published build turns on. This is not
/// API: it carries no stability promise, and an item is `pub` only because
/// its own module is unreachable without the feature.
#[cfg(feature = "internals")]
#[doc(hidden)]
pub mod internals {
    pub use crate::graph::book::internals as graph_book;
    pub use crate::graph::facts::internals as graph_facts;
    pub use crate::graph::iterator::internals as graph_iterator;
    pub use crate::isin_registry::env::internals as isin_registry_env;
    pub use crate::isin_registry::internals as isin_registry;
    pub use crate::marketdatakind::internals as marketdatakind;
}
// END GENERATED
