//! The standard header and trailer, as tag lists.
//!
//! Generated by `scripts/generate_fix_dictionary.py`; do not edit.
//!
//! Order rather than nesting: [`FixMsg`](crate::FixMsg) lays a message
//! flat, so both components are tag lists rather than Structs. They are
//! not registry entries either - a component carries no tag, and
//! `insert` admits only a field that does, so a synthetic tag would put
//! a fiction in the identity space. The component names and ids are
//! dropped; every field *in* them is an ordinary entry by its own tag.
//!
//! The lists are the union across every scraped version, because FIX
//! Latest alone is not enough: it no longer lists `SecureDataLen(90)`
//! in the header or `SignatureLength(93)` in the trailer, and a 4.2
//! message carries both. Requiredness rides the lineage rather than a
//! parallel table, because presence is already `nullable` on the field
//! a version resolves to.

/// The tags every version's standard header declares, in wire
/// order.
pub const STANDARD_HEADER_TAGS: [i32; 29] = [
    8, 9, 35, 1128, 1156, 1129, 49, 56, 115, 128, 90, 91, 34, 50, 142, 57, 143, 116, 144, 129, 145,
    43, 97, 52, 122, 212, 213, 347, 369,
];

/// The tags every version's standard trailer declares, in wire
/// order.
pub const STANDARD_TRAILER_TAGS: [i32; 3] = [93, 89, 10];
