//! Concrete floating-point scalars — every Apache Arrow single- and double-precision
//! float.
//!
//! One file per type (`float32.rs`, `float64.rs`), mirroring `yggdryl-dtype`'s
//! [`float`](yggdryl_dtype::float) module. The two scalars share the same shape (a
//! possibly-null native value with exact-or-error `as_*` accessors), so each is
//! generated by the focused crate-internal [`float_scalar!`] macro. It parallels the
//! integer family's `int_scalar!` — same Arrow round trip, [`ScalarFactory`](crate::ScalarFactory)
//! and byte codec — but with float-specific numeric accessors (a float reads as an
//! integer only when it is a whole number in range, and narrows to a smaller float
//! only when the value round-trips exactly) and **no `Eq` / `Hash`** (`f32` / `f64`
//! implement neither), so the scalar compares with `PartialEq`, `NaN`-aware.

use yggdryl_dtype::DataError;

/// A float read as the integer target `T`, exact-or-error: a whole number in `T`'s
/// range answers, anything with a fractional part, non-finite, or out of range errors
/// with [`DataError::InexactConversion`]. Shared by every `as_i*` / `as_u*` accessor
/// the [`float_scalar!`] macro generates. The float widens to `f64` first (`f32` →
/// `f64` is exact), then round-trips through `i128` to check for lost precision.
pub(crate) fn float_to_int<F, T>(value: F, target: &'static str) -> Result<T, DataError>
where
    F: Into<f64> + std::fmt::Display + Copy,
    T: TryFrom<i128>,
{
    let widened: f64 = value.into();
    let inexact = || DataError::InexactConversion {
        value: value.to_string(),
        target,
    };
    if !widened.is_finite() || widened.fract() != 0.0 {
        return Err(inexact());
    }
    let integer = widened as i128;
    // `as i128` saturates out-of-range floats and rounds huge ones, so confirm the
    // value survives the round trip before narrowing to the target width.
    if integer as f64 != widened {
        return Err(inexact());
    }
    T::try_from(integer).map_err(|_| inexact())
}

/// Generates a single, possibly-null float scalar `$ty` (e.g. `Float64Scalar`) over
/// the `yggdryl-dtype` data type `$dtype` (e.g. `Float64Type`, native `$native`),
/// with `$name` used in its documentation and `$array` the matching [`arrow_array`]
/// primitive array (`to_arrow_scalar` / `from_arrow`). Parallels the integer family's
/// `int_scalar!` but with float-specific `as_*` accessors and no `Eq` / `Hash`.
macro_rules! float_scalar {
    ($ty:ident, $dtype:ident, $native:ty, $name:literal, $array:ident) => {
        #[doc = concat!("A single, possibly-null `", $name, "` value (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq)]
        pub struct $ty {
            data_type: ::yggdryl_dtype::$dtype,
            value: Option<$native>,
        }

        // Hashed by bit pattern, so a float scalar can key a map: `-0.0` canonicalizes
        // to `+0.0` (hashing equal, as they compare equal), and a `NaN` hashes by its
        // bits though it is unequal to itself by value — the usual float-in-a-set
        // caveat. `Eq` is the pragmatic marker the type-erased holders already carry.
        impl ::std::cmp::Eq for $ty {}

        impl ::std::hash::Hash for $ty {
            fn hash<H: ::std::hash::Hasher>(&self, state: &mut H) {
                self.value
                    .map(|value| if value == 0.0 { 0 } else { value.to_bits() })
                    .hash(state);
            }
        }

        impl $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            pub fn new(value: $native) -> Self {
                Self {
                    data_type: ::yggdryl_dtype::$dtype,
                    value: Some(value),
                }
            }

            #[doc = concat!("A null `", $name, "` scalar.")]
            pub fn null() -> Self {
                Self {
                    data_type: ::yggdryl_dtype::$dtype,
                    value: None,
                }
            }
        }

        // A same-width float conversion (`f32` → `f32`, `f64` → `f64`) is an identity
        // `as`-cast, which clippy flags; the macro generates both float accessors
        // uniformly, so allow it once here.
        #[allow(clippy::unnecessary_cast)]
        impl $crate::Scalar for $ty {
            type DataType = ::yggdryl_dtype::$dtype;
            type Value = $native;
            fn data_type(&self) -> &::yggdryl_dtype::$dtype {
                &self.data_type
            }
            fn is_null(&self) -> bool {
                self.value.is_none()
            }
            fn value(&self) -> Option<&$native> {
                self.value.as_ref()
            }
            fn to_arrow_scalar(
                &self,
            ) -> $crate::arrow_array::Scalar<$crate::arrow_array::ArrayRef> {
                $crate::arrow_array::Scalar::new(match self.value {
                    // One element, no null buffer — cheaper than building through
                    // `Vec<Option<_>>`.
                    Some(value) => {
                        ::std::sync::Arc::new($crate::arrow_array::$array::from_iter_values(
                            [value],
                        ))
                    }
                    // Arrow arrays are immutable, so every null scalar shares one
                    // cached one-null array; a clone is a reference-count bump.
                    None => {
                        static NULL: ::std::sync::OnceLock<$crate::arrow_array::ArrayRef> =
                            ::std::sync::OnceLock::new();
                        NULL.get_or_init(|| {
                            ::std::sync::Arc::new($crate::arrow_array::$array::new_null(1))
                        })
                        .clone()
                    }
                })
            }
            fn from_arrow(
                array: &dyn $crate::arrow_array::Array,
            ) -> Result<Self, ::yggdryl_dtype::DataError> {
                // Fully-qualified `Array` calls: the trait is not in scope at the
                // macro's expansion site.
                let length = $crate::arrow_array::Array::len(array);
                if length != 1 {
                    return Err(::yggdryl_dtype::DataError::InvalidScalarLength { got: length });
                }
                let array = array
                    .as_any()
                    .downcast_ref::<$crate::arrow_array::$array>()
                    .ok_or_else(|| ::yggdryl_dtype::DataError::IncompatibleArrowType {
                        expected: stringify!($dtype).to_string(),
                        got: $crate::arrow_array::Array::data_type(array).to_string(),
                    })?;
                Ok(if $crate::arrow_array::Array::is_null(array, 0) {
                    Self::null()
                } else {
                    Self::new(array.value(0))
                })
            }
            // The little-endian value bytes — the source of the unchecked reinterpret
            // cast (this width's native `to_le_bytes`).
            fn value_le_bytes(&self) -> Result<Vec<u8>, ::yggdryl_dtype::DataError> {
                self.value
                    .map(|value| value.to_le_bytes().to_vec())
                    .ok_or(::yggdryl_dtype::DataError::NullValue)
            }
            fn as_i8(&self) -> Result<i8, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "i8")
            }
            fn as_i16(&self) -> Result<i16, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "i16")
            }
            fn as_i32(&self) -> Result<i32, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "i32")
            }
            fn as_i64(&self) -> Result<i64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "i64")
            }
            fn as_u8(&self) -> Result<u8, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "u8")
            }
            fn as_u16(&self) -> Result<u16, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "u16")
            }
            fn as_u32(&self) -> Result<u32, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "u32")
            }
            fn as_u64(&self) -> Result<u64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                $crate::float::float_to_int(value, "u64")
            }
            fn as_f16(&self) -> Result<::half::f16, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                let converted = ::half::f16::from_f64(value as f64);
                // Exact only: `NaN` narrows to `NaN` (its own inequality aside), a
                // finite value only when the narrowing round-trips.
                if value.is_nan() || converted.to_f64() as $native == value {
                    Ok(converted)
                } else {
                    Err(::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "f16",
                    })
                }
            }
            fn as_f32(&self) -> Result<f32, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                let converted = value as f32;
                // Exact only: `NaN` narrows to `NaN` (its own inequality aside), a
                // finite value only when the narrowing round-trips.
                if value.is_nan() || converted as $native == value {
                    Ok(converted)
                } else {
                    Err(::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "f32",
                    })
                }
            }
            fn as_f64(&self) -> Result<f64, ::yggdryl_dtype::DataError> {
                let value = self.value.ok_or(::yggdryl_dtype::DataError::NullValue)?;
                let converted = value as f64;
                if value.is_nan() || converted as $native == value {
                    Ok(converted)
                } else {
                    Err(::yggdryl_dtype::DataError::InexactConversion {
                        value: value.to_string(),
                        target: "f64",
                    })
                }
            }
        }

        impl $crate::TypedScalar<::yggdryl_dtype::$dtype, $native, $crate::arrow_array::$array>
            for $ty
        {
        }

        impl $crate::ScalarFactory<$native> for ::yggdryl_dtype::$dtype {
            type Scalar = $ty;
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            fn scalar(&self, value: $native) -> $ty {
                $ty::new(value)
            }
            #[doc = concat!("The null `", $name, "` scalar.")]
            fn null_scalar(&self) -> $ty {
                $ty::null()
            }
            #[doc = concat!("The default `", $name, "` scalar: a scalar holding `0.0`.")]
            fn default_scalar(&self) -> $ty {
                $ty::new(<$native>::default())
            }
        }

        impl ::core::convert::From<$native> for $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`.")]
            fn from(value: $native) -> Self {
                Self::new(value)
            }
        }

        impl ::core::convert::From<::core::option::Option<$native>> for $ty {
            #[doc = concat!("A `", $name, "` scalar holding `value`, or the null scalar for `None`.")]
            fn from(value: ::core::option::Option<$native>) -> Self {
                match value {
                    ::core::option::Option::Some(value) => Self::new(value),
                    ::core::option::Option::None => Self::null(),
                }
            }
        }
    };
}
pub(crate) use float_scalar;

mod float16;
mod float32;
mod float64;

pub use float16::Float16Scalar;
pub use float32::Float32Scalar;
pub use float64::Float64Scalar;
