from ..enums import CHARSETS as CHARSETS

__all__ = [
    "CHARSETS",
    "bom",
    "canonical_name",
    "decode",
    "decode_lossy",
    "encode",
    "from_bom",
]

def decode(charset: str, data: bytes) -> str: ...
def decode_lossy(charset: str, data: bytes) -> str: ...
def encode(charset: str, text: str) -> bytes: ...
def from_bom(data: bytes) -> tuple[str, int] | None: ...
def bom(charset: str) -> bytes | None: ...
def canonical_name(charset: str) -> str: ...
