//! Concrete integer fields — every Apache Arrow signed and unsigned integer.
//!
//! One file per type (`int8.rs`, …, `uint64.rs`), mirroring `yggdryl-dtype`'s
//! [`integer`](yggdryl_dtype::integer) module. The eight fields share the same
//! shape (a name paired with the fixed-width integer data type), so each is
//! generated by the focused crate-internal [`int_field!`] macro — keeping every
//! per-type file a single invocation while the logic lives in one place. The macro
//! also wires the [`FieldFactory`](crate::FieldFactory) so the data type builds its
//! field (`Int64Type.field("id", false)`).

/// Generates a nullable integer field `$ty` (e.g. `Int64Field`) over the
/// `yggdryl-dtype` data type `$dtype` (e.g. `Int64Type`, native `$native`), with
/// `$name` used in its documentation, and the matching
/// [`FieldFactory`](crate::FieldFactory) impl on the data type.
macro_rules! int_field {
    ($ty:ident, $dtype:ident, $native:ty, $name:literal) => {
        #[doc = concat!("A nullable `", $name, "` field: a name paired with the [`", stringify!($dtype), "`](::yggdryl_dtype::", stringify!($dtype), ") data type.")]
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $ty {
            name: String,
            data_type: ::yggdryl_dtype::$dtype,
            nullable: bool,
        }

        impl $ty {
            #[doc = concat!("A `", $name, "` field named `name`.")]
            pub fn new(name: impl Into<String>, nullable: bool) -> Self {
                Self {
                    name: name.into(),
                    data_type: ::yggdryl_dtype::$dtype,
                    nullable,
                }
            }
        }

        impl $crate::Field<::yggdryl_dtype::$dtype> for $ty {
            fn name(&self) -> &str {
                &self.name
            }
            fn data_type(&self) -> &::yggdryl_dtype::$dtype {
                &self.data_type
            }
            fn is_nullable(&self) -> bool {
                self.nullable
            }
            fn from_arrow(
                field: &$crate::arrow_schema::Field,
            ) -> Result<Self, ::yggdryl_dtype::DataError> {
                <::yggdryl_dtype::$dtype as ::yggdryl_dtype::DataType>::from_arrow(
                    field.data_type(),
                )?;
                $crate::field::validate_field_metadata(field, stringify!($dtype))?;
                Ok(Self::new(field.name(), field.is_nullable()))
            }
        }

        impl $crate::TypedField<::yggdryl_dtype::$dtype, $native> for $ty {}

        impl $crate::FieldFactory<$native> for ::yggdryl_dtype::$dtype {
            type Field = $ty;
            fn field(&self, name: impl Into<String>, nullable: bool) -> $ty {
                $ty::new(name, nullable)
            }
        }
    };
}
pub(crate) use int_field;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::Int16Field;
pub use int32::Int32Field;
pub use int64::Int64Field;
pub use int8::Int8Field;
pub use uint16::UInt16Field;
pub use uint32::UInt32Field;
pub use uint64::UInt64Field;
pub use uint8::UInt8Field;
