//! Concrete integer fields — every Apache Arrow signed and unsigned integer.
//!
//! One file per type (`int8.rs`, …, `uint64.rs`), mirroring `yggdryl-dtype`'s
//! [`integer`](yggdryl_dtype::integer) module. The eight fields share the same
//! shape (a name paired with the fixed-width integer data type), so each is
//! generated by the focused crate-internal [`int_field!`] macro — keeping every
//! per-type file a single invocation while the logic lives in one place.

/// Generates a nullable integer field `$ty` over the `yggdryl-dtype` data type of
/// the same name (native `$native`), with `$name` used in its documentation.
macro_rules! int_field {
    ($ty:ident, $native:ty, $name:literal) => {
        #[doc = concat!("A nullable `", $name, "` field: a name paired with the `", $name, "` data type.")]
        #[derive(Debug, Clone, PartialEq, Eq, Hash)]
        pub struct $ty {
            name: String,
            data_type: ::yggdryl_dtype::$ty,
            nullable: bool,
        }

        impl $ty {
            #[doc = concat!("A `", $name, "` field named `name`.")]
            pub fn new(name: impl Into<String>, nullable: bool) -> Self {
                Self {
                    name: name.into(),
                    data_type: ::yggdryl_dtype::$ty,
                    nullable,
                }
            }
        }

        impl $crate::RawField<::yggdryl_dtype::$ty> for $ty {
            fn name(&self) -> &str {
                &self.name
            }
            fn data_type(&self) -> &::yggdryl_dtype::$ty {
                &self.data_type
            }
            fn is_nullable(&self) -> bool {
                self.nullable
            }
            fn from_arrow(
                field: &$crate::arrow_schema::Field,
            ) -> Result<Self, ::yggdryl_dtype::DataError> {
                <::yggdryl_dtype::$ty as ::yggdryl_dtype::RawDataType>::from_arrow(
                    field.data_type(),
                )?;
                $crate::raw_field::validate_field_metadata(field, stringify!($ty))?;
                Ok(Self::new(field.name(), field.is_nullable()))
            }
        }

        impl $crate::Field<$native> for $ty {
            type Type = ::yggdryl_dtype::$ty;
        }
    };
}
pub(crate) use int_field;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::Int16;
pub use int32::Int32;
pub use int64::Int64;
pub use int8::Int8;
pub use uint16::UInt16;
pub use uint32::UInt32;
pub use uint64::UInt64;
pub use uint8::UInt8;
