//! [`DataType`] — the compile-time descriptor of a **fixed-width element type**.
//!
//! A `DataType` is the bridge between a [`DataTypeId`] tag and the native Rust scalar it
//! encodes/decodes. It carries no data — it is the *type* an [`Encoder`](super::Encoder) /
//! [`Decoder`](super::Decoder) work over and a [`Serie`](super::Serie) is parameterized by. The
//! concrete markers ([`Int32`](super::fixedbyte::Int32), [`Bit`](super::fixedbit::Bit), …) are
//! zero-sized and generated by the `fixed_*` macros.

use crate::datatype_id::DataTypeId;

/// A concrete **fixed-width data type** — the type-level tag `T` a typed value is generic over.
///
/// The associated [`Native`](DataType::Native) is the Rust scalar one element decodes to;
/// [`DATA_TYPE_ID`](DataType::DATA_TYPE_ID) is its stable tag. Everything else (widths, predicates)
/// derives from the tag, so an implementor is a one-line marker.
pub trait DataType: Copy + Default {
    /// The native Rust scalar one element reads/writes (`i32` for `Int32`, `bool` for `Bit`).
    /// `Default` is the value stored in a null slot (`0` / `false`).
    type Native: Copy + Default;

    /// The stable [`DataTypeId`] tag for this type.
    const DATA_TYPE_ID: DataTypeId;

    /// The tag — the runtime form of [`DATA_TYPE_ID`](DataType::DATA_TYPE_ID).
    fn data_type_id() -> DataTypeId {
        Self::DATA_TYPE_ID
    }

    /// The logical **bit width** of one element (`bool` → 1, `i32` → 32).
    fn bit_width() -> u64 {
        Self::DATA_TYPE_ID.bit_size()
    }

    /// The physical **byte width** of one element (`bool` → 1 byte, `i32` → 4); the storage stride.
    fn byte_width() -> u64 {
        Self::DATA_TYPE_ID.byte_size()
    }
}
