//! Concrete integer data types — every Apache Arrow signed and unsigned integer.
//!
//! One file per type (`int8.rs`, …, `uint64.rs`). The eight types share the same
//! shape (a fixed-width [`Primitive`](crate::Primitive) with a little-endian byte
//! codec), so each is generated by the focused crate-internal [`int_data_type!`]
//! macro — keeping every per-type file a single invocation while the logic lives
//! in one place. The matching fields and scalars live in `yggdryl-field` and
//! `yggdryl-scalar`, under the `Int64Field` / `Int64Scalar` naming convention.

/// Generates a fixed-width integer data type `$ty` (native Rust `$native`), with
/// `$name` its lowercase name, `$format` its Arrow C Data Interface format string,
/// `$width` its byte width and `$id` the matching [`DataTypeId`](crate::DataTypeId)
/// / [`arrow_schema::DataType`] variant.
macro_rules! int_data_type {
    ($ty:ident, $native:ty, $name:literal, $format:literal, $width:literal, $id:ident) => {
        #[doc = concat!("The Apache Arrow `", $name, "` data type: a fixed-width integer primitive (native `", stringify!($native), "`).")]
        #[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Hash)]
        pub struct $ty;

        impl $ty {
            /// This type's [`DataTypeId`](crate::DataTypeId).
            pub const ID: $crate::DataTypeId = $crate::DataTypeId::$id;
        }

        impl $crate::DataType for $ty {
            fn name(&self) -> &str {
                $name
            }
            fn arrow_format(&self) -> String {
                $format.to_string()
            }
            fn byte_width(&self) -> Option<usize> {
                Some($width)
            }
            fn to_arrow(&self) -> $crate::arrow_schema::DataType {
                $crate::arrow_schema::DataType::$id
            }
            fn from_arrow(
                data_type: &$crate::arrow_schema::DataType,
            ) -> Result<Self, $crate::DataError> {
                match data_type {
                    $crate::arrow_schema::DataType::$id => Ok(Self),
                    other => Err($crate::DataError::IncompatibleArrowType {
                        expected: stringify!($ty).to_string(),
                        got: other.to_string(),
                    }),
                }
            }
        }

        impl $crate::TypedDataType<$native> for $ty {
            fn native_to_bytes(&self, value: &$native) -> Vec<u8> {
                value.to_le_bytes().to_vec()
            }
            fn default_value(&self) -> $native {
                <$native>::default()
            }
            fn native_from_bytes(&self, bytes: &[u8]) -> Result<$native, $crate::DataError> {
                let array: [u8; $width] =
                    bytes
                        .try_into()
                        .map_err(|_| $crate::DataError::InvalidByteLength {
                            expected: $width,
                            got: bytes.len(),
                        })?;
                Ok(<$native>::from_le_bytes(array))
            }
        }

        impl $crate::Primitive for $ty {}
    };
}
pub(crate) use int_data_type;

mod int16;
mod int32;
mod int64;
mod int8;
mod uint16;
mod uint32;
mod uint64;
mod uint8;

pub use int16::Int16Type;
pub use int32::Int32Type;
pub use int64::Int64Type;
pub use int8::Int8Type;
pub use uint16::UInt16Type;
pub use uint32::UInt32Type;
pub use uint64::UInt64Type;
pub use uint8::UInt8Type;
