//! `fixedbyte` — **fixed-length, byte-granular** element types: the integers and floats.
//!
//! Every type here is a whole number of bytes wide, so it packs at a byte stride and reads/writes
//! through the source's vectorized typed array kernels (`pwrite_i32_array` / `pread_i32_array`, …)
//! and reduces through its [`Aggregate`](crate::io::memory::Aggregate) kernels. The zero-sized
//! marker + its [`Encoder`](super::Encoder) / [`Decoder`](super::Decoder) / [`Reduce`](super::Reduce)
//! impls are generated by the [`fixed_numeric!`] rule — one line per type.

/// **The generic implementation rule for a fixed-width numeric type.** Emits the zero-sized marker
/// plus its [`DataType`](super::DataType), [`Encoder`](super::Encoder), [`Decoder`](super::Decoder),
/// and [`Reduce`](super::Reduce) impls: encode/decode forward to the source's typed **array** kernels
/// (a scalar op is a one-element slice), the reductions to its [`Aggregate`](crate::io::memory::Aggregate)
/// kernels. Params: `Marker, native, DataTypeId, Sum, pwrite_array, pread_array, sum, min, max, mean`.
macro_rules! fixed_numeric {
    (
        $(#[$doc:meta])*
        $marker:ident, $native:ty, $id:ident, $sum:ty,
        $warr:ident, $rarr:ident, $summ:ident, $minm:ident, $maxm:ident, $meanm:ident
    ) => {
        $(#[$doc])*
        #[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
        pub struct $marker;

        impl $crate::typed::DataType for $marker {
            type Native = $native;
            const DATA_TYPE_ID: $crate::datatype_id::DataTypeId =
                $crate::datatype_id::DataTypeId::$id;
        }

        impl $crate::typed::Encoder for $marker {
            fn encode<W: $crate::io::memory::IOBase>(
                dst: &mut W,
                index: u64,
                value: $native,
            ) -> Result<(), $crate::io::memory::IoError> {
                <Self as $crate::typed::Encoder>::encode_slice(dst, index, &[value])
            }
            fn encode_slice<W: $crate::io::memory::IOBase>(
                dst: &mut W,
                start: u64,
                values: &[$native],
            ) -> Result<(), $crate::io::memory::IoError> {
                dst.$warr(start * core::mem::size_of::<$native>() as u64, values)
            }
        }

        impl $crate::typed::Decoder for $marker {
            fn decode<R: $crate::io::memory::IOBase>(
                src: &R,
                index: u64,
            ) -> Result<$native, $crate::io::memory::IoError> {
                let mut out = [<$native>::default(); 1];
                <Self as $crate::typed::Decoder>::decode_slice(src, index, &mut out)?;
                Ok(out[0])
            }
            fn decode_slice<R: $crate::io::memory::IOBase>(
                src: &R,
                start: u64,
                out: &mut [$native],
            ) -> Result<(), $crate::io::memory::IoError> {
                src.$rarr(start * core::mem::size_of::<$native>() as u64, out)
            }
        }

        impl $crate::typed::Reduce for $marker {
            type Sum = $sum;
            fn sum<R: $crate::io::memory::IOBase>(
                src: &R,
                start: u64,
                count: usize,
            ) -> Result<$sum, $crate::io::memory::IoError> {
                $crate::io::memory::Aggregate::$summ(
                    src,
                    start * core::mem::size_of::<$native>() as u64,
                    count,
                )
            }
            fn min<R: $crate::io::memory::IOBase>(
                src: &R,
                start: u64,
                count: usize,
            ) -> Result<Option<$native>, $crate::io::memory::IoError> {
                $crate::io::memory::Aggregate::$minm(
                    src,
                    start * core::mem::size_of::<$native>() as u64,
                    count,
                )
            }
            fn max<R: $crate::io::memory::IOBase>(
                src: &R,
                start: u64,
                count: usize,
            ) -> Result<Option<$native>, $crate::io::memory::IoError> {
                $crate::io::memory::Aggregate::$maxm(
                    src,
                    start * core::mem::size_of::<$native>() as u64,
                    count,
                )
            }
            fn mean<R: $crate::io::memory::IOBase>(
                src: &R,
                start: u64,
                count: usize,
            ) -> Result<Option<f64>, $crate::io::memory::IoError> {
                $crate::io::memory::Aggregate::$meanm(
                    src,
                    start * core::mem::size_of::<$native>() as u64,
                    count,
                )
            }
        }
    };
}

mod float;
mod integer;

pub use float::{Float32, Float64};
pub use integer::{Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8};
