//! [`Column`] — the **erased column carrier**: a tagged union over every concrete data column, so a
//! heterogeneous set of children can coexist inside a [`StructSerie`]. It is the runtime parallel of
//! the compile-time-typed [`FixedSerie`] / [`VarSerie`] / [`FixedSizeSerie`] — the keystone that lets
//! the nested layer hold columns of *different* types side by side.
//!
//! A concrete column ([`FixedSerie<Int64>`](FixedSerie), a [`VarSerie<Utf8>`](VarSerie), …) becomes a
//! `Column` through [`From`] (`Column::from(serie)`); the reverse — reaching the concrete column back
//! out for a **deep, in-place mutation** — is a plain match on the public variant
//! (`if let Column::Int64(serie) = column { serie.set(0, 999)? }`), because the variant *holds* the
//! concrete series. The leaf arms are generated by the [`leaf_columns!`] rule.

use crate::datatype_id::DataTypeId;
use crate::typed::fixedbit::Bit;
use crate::typed::fixedbyte::{
    Decimal128, Decimal256, Decimal32, Decimal64, FixedBinary, FixedSizeSerie, FixedUtf8, Float32,
    Float64, Int128, Int16, Int32, Int64, Int8, UInt128, UInt16, UInt32, UInt64, UInt8,
};
use crate::typed::nested::{ColumnField, ListSerie, MapSerie, StructSerie, Value};
use crate::typed::varbyte::{Binary, LargeBinary, LargeUtf8, Utf8};
use crate::typed::{FixedSerie, HeaderField, NullSerie, Scalar, VarSerie};

/// Generates the [`Column`] enum's **leaf arms** and their uniform method dispatch + [`From`] impls
/// from a table of `Variant: CarrierType => ValueWrap` rows — one row per concrete flat column. Every
/// leaf delegates `len` / `is_null` / `null_count` / `data_type_id` to the carrier's
/// [`Scalar`] surface, wraps `get` into the matching [`Value`] variant, and reports
/// [`ColumnField::Leaf`] for its field. The `Null` and `Struct` arms are spelled out (they are not
/// carrier-backed leaves).
macro_rules! leaf_columns {
    ( $( $(#[$doc:meta])* $variant:ident : $carrier:ty => $wrap:path ),+ $(,)? ) => {
        /// A single data column, erased over its element type. `Null` is a bufferless run of `n`
        /// nulls; each leaf variant holds one concrete flat carrier; `Struct` / `List` / `Map`
        /// recurse into a nested [`StructSerie`] / [`ListSerie`] / [`MapSerie`].
        #[non_exhaustive]
        pub enum Column {
            /// `n` null elements with **no backing buffer** — the cheapest all-null child.
            Null(usize),
            $(
                $(#[$doc])*
                $variant($carrier),
            )+
            /// A **nested struct** child — recurses into a [`StructSerie`].
            Struct(StructSerie),
            /// A **nested list** child — recurses into a [`ListSerie`] (a flattened child column
            /// plus offsets).
            List(ListSerie),
            /// A **nested map** child — recurses into a [`MapSerie`] (a two-column key / value
            /// entries struct plus offsets).
            Map(MapSerie),
        }

        impl Column {
            /// The number of elements in the column.
            pub fn len(&self) -> usize {
                match self {
                    Column::Null(n) => *n,
                    $( Column::$variant(serie) => serie.len(), )+
                    Column::Struct(serie) => serie.len(),
                    Column::List(serie) => serie.len(),
                    Column::Map(serie) => serie.len(),
                }
            }

            /// Whether the element at `index` is **null**. A [`Null`](Column::Null) column is null for
            /// every in-range index.
            pub fn is_null(&self, index: usize) -> bool {
                match self {
                    Column::Null(n) => index < *n,
                    $( Column::$variant(serie) => serie.is_null(index), )+
                    Column::Struct(serie) => serie.is_null(index),
                    Column::List(serie) => serie.is_null(index),
                    Column::Map(serie) => serie.is_null(index),
                }
            }

            /// How many elements are null.
            pub fn null_count(&self) -> usize {
                match self {
                    Column::Null(n) => *n,
                    $( Column::$variant(serie) => serie.null_count(), )+
                    Column::Struct(serie) => serie.null_count(),
                    Column::List(serie) => serie.null_count(),
                    Column::Map(serie) => serie.null_count(),
                }
            }

            /// The element at `index`, erased to a [`Value`] — [`Value::Null`] when the slot is null
            /// or out of range.
            pub fn get(&self, index: usize) -> Value {
                match self {
                    Column::Null(_) => Value::Null,
                    $( Column::$variant(serie) => match serie.get(index) {
                        Some(value) => $wrap(value),
                        None => Value::Null,
                    }, )+
                    Column::Struct(serie) => match serie.row(index) {
                        Some(row) if !row.is_null() => Value::Row(row),
                        _ => Value::Null,
                    },
                    Column::List(serie) => serie.get(index),
                    Column::Map(serie) => serie.get(index),
                }
            }

            /// The element [`DataTypeId`] — [`Null`](DataTypeId::Null) (the typed all-null) for a
            /// bufferless [`Null`](Column::Null) column, or the nested tag
            /// ([`Struct`](DataTypeId::Struct) / [`List`](DataTypeId::List) / [`Map`](DataTypeId::Map))
            /// for a nested child.
            pub fn data_type_id(&self) -> DataTypeId {
                match self {
                    Column::Null(_) => DataTypeId::Null,
                    $( Column::$variant(serie) => serie.data_type_id(), )+
                    Column::Struct(_) => DataTypeId::Struct,
                    Column::List(_) => DataTypeId::List,
                    Column::Map(_) => DataTypeId::Map,
                }
            }

            /// The column's [`ColumnField`] descriptor — [`Leaf`](ColumnField::Leaf) for a flat
            /// column, or the nested field ([`Struct`](ColumnField::Struct) /
            /// [`List`](ColumnField::List) / [`Map`](ColumnField::Map)) for a nested child.
            pub fn field(&self) -> ColumnField {
                match self {
                    Column::Null(_) => {
                        ColumnField::Leaf(HeaderField::new(None, DataTypeId::Null, true))
                    }
                    $( Column::$variant(serie) => ColumnField::Leaf(serie.field()), )+
                    Column::Struct(serie) => ColumnField::Struct(serie.field()),
                    Column::List(serie) => ColumnField::List(serie.field()),
                    Column::Map(serie) => ColumnField::Map(serie.field()),
                }
            }

            /// The column **name**, if set (read from the carrier's field metadata).
            pub fn name(&self) -> Option<&str> {
                match self {
                    Column::Null(_) => None,
                    $( Column::$variant(serie) => serie.name(), )+
                    Column::Struct(serie) => serie.name(),
                    Column::List(serie) => serie.name(),
                    Column::Map(serie) => serie.name(),
                }
            }

            /// Appends a **null** element (growing the column by one row) — the erased dispatch every
            /// child of a struct row gets when the whole row is nulled.
            pub fn push_null(&mut self) {
                match self {
                    Column::Null(n) => *n += 1,
                    $( Column::$variant(serie) => serie.push_null(), )+
                    Column::Struct(serie) => serie.push_null(),
                    Column::List(serie) => serie.push_null(),
                    Column::Map(serie) => serie.push_null(),
                }
            }
        }

        $(
            impl From<$carrier> for Column {
                fn from(serie: $carrier) -> Self {
                    Column::$variant(serie)
                }
            }
        )+
    };
}

leaf_columns! {
    /// A signed 8-bit integer column.
    Int8: FixedSerie<Int8> => Value::Int8,
    /// An unsigned 8-bit integer column.
    UInt8: FixedSerie<UInt8> => Value::UInt8,
    /// A signed 16-bit integer column.
    Int16: FixedSerie<Int16> => Value::Int16,
    /// An unsigned 16-bit integer column.
    UInt16: FixedSerie<UInt16> => Value::UInt16,
    /// A signed 32-bit integer column.
    Int32: FixedSerie<Int32> => Value::Int32,
    /// An unsigned 32-bit integer column.
    UInt32: FixedSerie<UInt32> => Value::UInt32,
    /// A signed 64-bit integer column.
    Int64: FixedSerie<Int64> => Value::Int64,
    /// An unsigned 64-bit integer column.
    UInt64: FixedSerie<UInt64> => Value::UInt64,
    /// A signed 128-bit integer column.
    Int128: FixedSerie<Int128> => Value::Int128,
    /// An unsigned 128-bit integer column.
    UInt128: FixedSerie<UInt128> => Value::UInt128,
    /// A 32-bit float column.
    Float32: FixedSerie<Float32> => Value::Float32,
    /// A 64-bit float column.
    Float64: FixedSerie<Float64> => Value::Float64,
    /// A boolean column (one bit per element).
    Bool: FixedSerie<Bit> => Value::Bool,
    /// A 32-bit fixed-point decimal column.
    Decimal32: FixedSerie<Decimal32> => Value::Decimal32,
    /// A 64-bit fixed-point decimal column.
    Decimal64: FixedSerie<Decimal64> => Value::Decimal64,
    /// A 128-bit fixed-point decimal column.
    Decimal128: FixedSerie<Decimal128> => Value::Decimal128,
    /// A 256-bit fixed-point decimal column.
    Decimal256: FixedSerie<Decimal256> => Value::Decimal256,
    /// A variable-length binary column (`i32` offsets).
    Binary: VarSerie<Binary> => Value::Binary,
    /// A variable-length UTF-8 column (`i32` offsets).
    Utf8: VarSerie<Utf8> => Value::Utf8,
    /// A large variable-length binary column (`i64` offsets).
    LargeBinary: VarSerie<LargeBinary> => Value::Binary,
    /// A large variable-length UTF-8 column (`i64` offsets).
    LargeUtf8: VarSerie<LargeUtf8> => Value::Utf8,
    /// A fixed-size binary column (a fixed byte width per element).
    FixedBinary: FixedSizeSerie<FixedBinary> => Value::Binary,
    /// A fixed-size UTF-8 column (a fixed byte width per element).
    FixedUtf8: FixedSizeSerie<FixedUtf8> => Value::Utf8,
}

impl Column {
    /// A column of `n` **null** elements with no backing buffer — the cheapest all-null child.
    pub fn null(n: usize) -> Self {
        Column::Null(n)
    }

    /// Whether the column has no elements.
    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }
}

impl From<NullSerie> for Column {
    /// Erases a typed [`NullSerie`] into the bufferless [`Column::Null`] of the same length. The
    /// null column has no values to carry, so only its length crosses over.
    fn from(serie: NullSerie) -> Self {
        Column::Null(serie.len())
    }
}

impl From<StructSerie> for Column {
    fn from(serie: StructSerie) -> Self {
        Column::Struct(serie)
    }
}

impl From<ListSerie> for Column {
    fn from(serie: ListSerie) -> Self {
        Column::List(serie)
    }
}

impl From<MapSerie> for Column {
    fn from(serie: MapSerie) -> Self {
        Column::Map(serie)
    }
}
