// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */

const { readFileSync } = require('fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) {
      musl = isMuslFromReport()
    }
    if (musl === null) {
      musl = isMuslFromChildProcess()
    }
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')

const isMuslFromFilesystem = () => {
  try {
    return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl')
  } catch {
    return null
  }
}

const isMuslFromReport = () => {
  let report = null
  if (process.report && typeof process.report.getReport === 'function') {
    process.report.excludeNetwork = true
    report = process.report.getReport()
  }
  if (!report) {
    return null
  }
  if (report.header && report.header.glibcVersionRuntime) {
    return false
  }
  if (Array.isArray(report.sharedObjects)) {
    if (report.sharedObjects.some(isFileMusl)) {
      return true
    }
  }
  return false
}

const isMuslFromChildProcess = () => {
  try {
    return require('child_process').execSync('ldd --version', { encoding: 'utf8' }).includes('musl')
  } catch (e) {
    // If we reach this case, we don't know if the system is musl or not, so is better to just fallback to false
    return false
  }
}

function requireNative() {
  if (process.env.NAPI_RS_NATIVE_LIBRARY_PATH) {
    try {
      return require(process.env.NAPI_RS_NATIVE_LIBRARY_PATH);
    } catch (err) {
      loadErrors.push(err)
    }
  } else if (process.platform === 'android') {
    if (process.arch === 'arm64') {
      try {
        return require('./yggdryl.android-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./yggdryl.android-arm-eabi.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Android ${process.arch}`))
    }
  } else if (process.platform === 'win32') {
    if (process.arch === 'x64') {
      if ((process.config && process.config.variables && process.config.variables.shlib_suffix === 'dll.a') || (process.config && process.config.variables && process.config.variables.node_target_type === 'shared_library')) {
        try {
        return require('./yggdryl.win32-x64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
      } else {
        try {
        return require('./yggdryl.win32-x64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
      }
    } else if (process.arch === 'ia32') {
      try {
        return require('./yggdryl.win32-ia32-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./yggdryl.win32-arm64-msvc.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Windows: ${process.arch}`))
    }
  } else if (process.platform === 'darwin') {
    try {
      return require('./yggdryl.darwin-universal.node')
    } catch (e) {
      loadErrors.push(e)
    }
    if (process.arch === 'x64') {
      try {
        return require('./yggdryl.darwin-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./yggdryl.darwin-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on macOS: ${process.arch}`))
    }
  } else if (process.platform === 'freebsd') {
    if (process.arch === 'x64') {
      try {
        return require('./yggdryl.freebsd-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm64') {
      try {
        return require('./yggdryl.freebsd-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on FreeBSD: ${process.arch}`))
    }
  } else if (process.platform === 'linux') {
    if (process.arch === 'x64') {
      if (isMusl()) {
        try {
          return require('./yggdryl.linux-x64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./yggdryl.linux-x64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm64') {
      if (isMusl()) {
        try {
          return require('./yggdryl.linux-arm64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./yggdryl.linux-arm64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'arm') {
      if (isMusl()) {
        try {
          return require('./yggdryl.linux-arm-musleabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./yggdryl.linux-arm-gnueabihf.node')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'loong64') {
      if (isMusl()) {
        try {
          return require('./yggdryl.linux-loong64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./yggdryl.linux-loong64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'riscv64') {
      if (isMusl()) {
        try {
          return require('./yggdryl.linux-riscv64-musl.node')
        } catch (e) {
          loadErrors.push(e)
        }
      } else {
        try {
          return require('./yggdryl.linux-riscv64-gnu.node')
        } catch (e) {
          loadErrors.push(e)
        }
      }
    } else if (process.arch === 'ppc64') {
      try {
        return require('./yggdryl.linux-ppc64-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 's390x') {
      try {
        return require('./yggdryl.linux-s390x-gnu.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on Linux: ${process.arch}`))
    }
  } else if (process.platform === 'openharmony') {
    if (process.arch === 'arm64') {
      try {
        return require('./yggdryl.openharmony-arm64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'x64') {
      try {
        return require('./yggdryl.openharmony-x64.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else if (process.arch === 'arm') {
      try {
        return require('./yggdryl.openharmony-arm.node')
      } catch (e) {
        loadErrors.push(e)
      }
    } else {
      loadErrors.push(new Error(`Unsupported architecture on OpenHarmony: ${process.arch}`))
    }
  } else {
    loadErrors.push(new Error(`Unsupported OS: ${process.platform}, architecture: ${process.arch}`))
  }
}

function createLoadErrorChain(errors) {
  return errors.reduce((previous, current) => {
    let message
    try {
      message =
        current && typeof current.message === 'string'
          ? current.message
          : String(current)
    } catch {
      message = 'Unknown error'
    }
    const error = new Error(message)
    error.cause = previous
    return error
  }, null)
}

// NAPI_RS_FORCE_WASI is a tri-state flag:
//   unset / any other value → native binding preferred, WASI is only a fallback
//   'true'                   → prefer WASI, but retain native as a lazy fallback
//   'error'                  → require WASI without initializing a native fallback
// Treating any non-empty string as truthy (the historical behavior) meant
// NAPI_RS_FORCE_WASI=false, NAPI_RS_FORCE_WASI=0, etc. inadvertently triggered
// the WASI path, causing ENOENT for packages shipped without a .wasi.cjs file.
//
// NAPI_RS_WASI_FLAVOR selects one exact generated flavor and implies strict
// WASI loading. It never crosses into another flavor or falls back to native.
const __napiWasiFlavors = ["wasm32-wasi"]
const __napiWasiFlavor = process.env.NAPI_RS_WASI_FLAVOR
const __napiWasiFlavorRequested =
  typeof __napiWasiFlavor === 'string' && __napiWasiFlavor.length > 0
if (
  __napiWasiFlavorRequested &&
  __napiWasiFlavors.indexOf(__napiWasiFlavor) === -1
) {
  throw new Error(
    'Unsupported WASI flavor "' +
      __napiWasiFlavor +
      '". Available flavors: ' +
      __napiWasiFlavors.join(', '),
  )
}
const forceWasiError = process.env.NAPI_RS_FORCE_WASI === 'error'
const forceWasi =
  process.env.NAPI_RS_FORCE_WASI === 'true' ||
  forceWasiError ||
  __napiWasiFlavorRequested

if (!forceWasi) {
  nativeBinding = requireNative()
}

if (!nativeBinding || forceWasi) {
  let wasiBinding = null
  let wasiBindingLoaded = false
  const wasiBindingErrors = []
  const __napiWasiResolveCandidate = (specifier, isPackage, localArtifacts) => {
    try {
      require.resolve(specifier)
    } catch (resolveError) {
      if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
        throw resolveError
      }
      if (isPackage) {
        try {
          require.resolve(specifier + '/package.json')
        } catch (packageError) {
          if (packageError && packageError.code === 'MODULE_NOT_FOUND') {
            return resolveError
          }
          // An exports restriction proves the package exists even when its
          // package.json is not public. Preserve the root resolution failure.
          throw resolveError
        }
        // The package exists but its main/export target is broken.
        throw resolveError
      }
      return resolveError
    }
    if (localArtifacts) {
      let artifactError = null
      for (let i = 0; i < localArtifacts.length; i++) {
        try {
          require.resolve(localArtifacts[i])
          return null
        } catch (resolveError) {
          if (!resolveError || resolveError.code !== 'MODULE_NOT_FOUND') {
            throw resolveError
          }
          artifactError = resolveError
        }
      }
      return artifactError
    }
    return null
  }
  if (!wasiBindingLoaded && (!__napiWasiFlavorRequested || __napiWasiFlavor === "wasm32-wasi")) {
    let candidateError = null
    let candidateFailed = false
    try {
      candidateError = __napiWasiResolveCandidate('./yggdryl.wasi.cjs', false, ["./yggdryl.wasm32-wasi.debug.wasm","./yggdryl.wasm32-wasi.wasm"])
      candidateFailed = candidateError !== null
      if (!candidateFailed) {
        wasiBinding = require('./yggdryl.wasi.cjs')
        nativeBinding = wasiBinding
        wasiBindingLoaded = true
      }
    } catch (err) {
      candidateError = err
      candidateFailed = true
    }
    if (candidateFailed) {
      wasiBindingErrors.push(candidateError)
      loadErrors.push(candidateError)
    }
  }
  if (
    !wasiBindingLoaded &&
    forceWasi &&
    !forceWasiError &&
    !__napiWasiFlavorRequested
  ) {
    nativeBinding = requireNative()
  }
  if ((forceWasiError || __napiWasiFlavorRequested) && !wasiBindingLoaded) {
    const error = new Error(
      __napiWasiFlavorRequested
        ? 'WASI binding for flavor "' + __napiWasiFlavor + '" not found'
        : 'WASI binding not found and NAPI_RS_FORCE_WASI is set to error',
    )
    error.cause = createLoadErrorChain(wasiBindingErrors)
    throw error
  }
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const error = new Error(
      `Cannot find native binding. ` +
        `npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). ` +
        'Please try `npm i` again after removing both package-lock.json and node_modules directory.',
    )
    // assign instead of the `new Error(message, { cause })` options form,
    // which Node < 16.9 silently ignores
    error.cause = createLoadErrorChain(loadErrors)
    throw error
  }
  throw new Error(`Failed to load native binding`)
}

module.exports = nativeBinding
module.exports.AvroBlock = nativeBinding.AvroBlock
module.exports.JsAvroBlock = nativeBinding.JsAvroBlock
module.exports.AvroBlocks = nativeBinding.AvroBlocks
module.exports.JsAvroBlocks = nativeBinding.JsAvroBlocks
module.exports.AvroSchema = nativeBinding.AvroSchema
module.exports.JsAvroSchema = nativeBinding.JsAvroSchema
module.exports.BatchReader = nativeBinding.BatchReader
module.exports.JsBatchReader = nativeBinding.JsBatchReader
module.exports.Bound = nativeBinding.Bound
module.exports.JsBound = nativeBinding.JsBound
module.exports.BoundStatement = nativeBinding.BoundStatement
module.exports.JsBoundStatement = nativeBinding.JsBoundStatement
module.exports.ByteIterator = nativeBinding.ByteIterator
module.exports.JsByteIterator = nativeBinding.JsByteIterator
module.exports.Catalog = nativeBinding.Catalog
module.exports.JsCatalog = nativeBinding.JsCatalog
module.exports.Compaction = nativeBinding.Compaction
module.exports.JsCompaction = nativeBinding.JsCompaction
module.exports.DataFile = nativeBinding.DataFile
module.exports.JsDataFile = nativeBinding.JsDataFile
module.exports.DataType = nativeBinding.DataType
module.exports.JsDataType = nativeBinding.JsDataType
module.exports.DifferenceIterator = nativeBinding.DifferenceIterator
module.exports.JsDifferenceIterator = nativeBinding.JsDifferenceIterator
module.exports.Expression = nativeBinding.Expression
module.exports.JsExpression = nativeBinding.JsExpression
module.exports.Field = nativeBinding.Field
module.exports.JsField = nativeBinding.JsField
module.exports.IcebergNames = nativeBinding.IcebergNames
module.exports.JsIcebergNames = nativeBinding.JsIcebergNames
module.exports.IcebergOptions = nativeBinding.IcebergOptions
module.exports.JsIcebergOptions = nativeBinding.JsIcebergOptions
module.exports.IOBase = nativeBinding.IOBase
module.exports.JsIOBase = nativeBinding.JsIOBase
module.exports.IOCursor = nativeBinding.IOCursor
module.exports.JsIOCursor = nativeBinding.JsIOCursor
module.exports.LineIterator = nativeBinding.LineIterator
module.exports.JsLineIterator = nativeBinding.JsLineIterator
module.exports.Listing = nativeBinding.Listing
module.exports.JsListing = nativeBinding.JsListing
module.exports.ManifestFile = nativeBinding.ManifestFile
module.exports.JsManifestFile = nativeBinding.JsManifestFile
module.exports.MediaType = nativeBinding.MediaType
module.exports.JsMediaType = nativeBinding.JsMediaType
module.exports.MimeType = nativeBinding.MimeType
module.exports.JsMimeType = nativeBinding.JsMimeType
module.exports.Namespace = nativeBinding.Namespace
module.exports.JsNamespace = nativeBinding.JsNamespace
module.exports.Namespaces = nativeBinding.Namespaces
module.exports.JsNamespaces = nativeBinding.JsNamespaces
module.exports.PartitionField = nativeBinding.PartitionField
module.exports.JsPartitionField = nativeBinding.JsPartitionField
module.exports.PartitionSpec = nativeBinding.PartitionSpec
module.exports.JsPartitionSpec = nativeBinding.JsPartitionSpec
module.exports.ProtocolMetadata = nativeBinding.ProtocolMetadata
module.exports.JsProtocolMetadata = nativeBinding.JsProtocolMetadata
module.exports.RecordOptions = nativeBinding.RecordOptions
module.exports.JsRecordOptions = nativeBinding.JsRecordOptions
module.exports.Scalar = nativeBinding.Scalar
module.exports.JsScalar = nativeBinding.JsScalar
module.exports.ScalarIterator = nativeBinding.ScalarIterator
module.exports.JsScalarIterator = nativeBinding.JsScalarIterator
module.exports.ScanPlan = nativeBinding.ScanPlan
module.exports.JsScanPlan = nativeBinding.JsScanPlan
module.exports.SchemaUpdate = nativeBinding.SchemaUpdate
module.exports.JsSchemaUpdate = nativeBinding.JsSchemaUpdate
module.exports.Snapshot = nativeBinding.Snapshot
module.exports.JsSnapshot = nativeBinding.JsSnapshot
module.exports.SnapshotRef = nativeBinding.SnapshotRef
module.exports.JsSnapshotRef = nativeBinding.JsSnapshotRef
module.exports.Statement = nativeBinding.Statement
module.exports.JsStatement = nativeBinding.JsStatement
module.exports.Table = nativeBinding.Table
module.exports.JsTable = nativeBinding.JsTable
module.exports.Tables = nativeBinding.Tables
module.exports.JsTables = nativeBinding.JsTables
module.exports.Timezone = nativeBinding.Timezone
module.exports.JsTimezone = nativeBinding.JsTimezone
module.exports.Uri = nativeBinding.Uri
module.exports.JsUri = nativeBinding.JsUri
module.exports.Url = nativeBinding.Url
module.exports.JsUrl = nativeBinding.JsUrl
module.exports.Urn = nativeBinding.Urn
module.exports.JsUrn = nativeBinding.JsUrn
module.exports.codecInferFormat = nativeBinding.codecInferFormat
module.exports.codecNormalizeFormat = nativeBinding.codecNormalizeFormat
