"""Generate a notebook of every documentation page's examples, one per language.

The cells come from the same fenced blocks that ``scripts/check_docs_examples.py``
compiles and runs, so a notebook cannot drift from a tested example: regenerating
is the only way its code changes. The notebooks are written unexecuted, because
nothing here runs a kernel and a reader downloads them to run them anyway, and
each page links to the ones it produced.

Every code cell is an example the checker ran. What a reader needs before running
one - a kernel, a crate, a package - is prose in a markdown cell rather than a
cell of its own, so nothing untested is ever presented as runnable.

Usage:
    python scripts/build_docs_notebooks.py            # regenerate and relink
    python scripts/build_docs_notebooks.py --check    # report staleness, write nothing
"""

from __future__ import annotations

import argparse
import json
import os
import pathlib
import re
import sys
import textwrap
from typing import NamedTuple

# The extraction lives with the checker that executes the blocks, so a cell here
# and the example that passed there are the same text rather than two readings of
# the same page. Both scripts run as `python scripts/<name>.py`, which is what
# puts this directory on the import path.
from check_docs_examples import DOCS, LANGUAGES, ROOT, Block, blocks, headings, runnable, slug

NOTEBOOKS = DOCS / "notebooks"
START = "<!-- notebooks: generated by scripts/build_docs_notebooks.py -->"
END = "<!-- /notebooks -->"


class Kernel(NamedTuple):
    """How one language names itself in a notebook, and what a reader needs first."""

    title: str
    kernelspec: dict[str, str]
    language_info: dict[str, str]
    setup: str


KERNELS = {
    "rust": Kernel(
        title="Rust",
        kernelspec={"display_name": "Rust", "language": "rust", "name": "rust"},
        language_info={
            "codemirror_mode": "rust",
            "file_extension": ".rs",
            "mimetype": "text/rust",
            "name": "rust",
            "pygments_lexer": "rust",
            "version": "",
        },
        setup=textwrap.dedent(
            """\
            The cells are unexecuted and expect the
            [evcxr](https://github.com/evcxr/evcxr) kernel. Declare the crate once, in
            a cell of your own, before running them:

            ```rust
            :dep yggdryl = { version = "0.1", features = ["parquet", "iceberg"] }
            ```
            """
        ),
    ),
    "python": Kernel(
        title="Python",
        kernelspec={"display_name": "Python 3", "language": "python", "name": "python3"},
        language_info={
            "codemirror_mode": "python",
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "pygments_lexer": "ipython3",
            "version": "",
        },
        setup=textwrap.dedent(
            """\
            The cells are unexecuted and run on any Python 3 kernel with the package
            installed:

            ```console
            pip install yggdryl
            ```
            """
        ),
    ),
    "javascript": Kernel(
        title="JavaScript",
        kernelspec={
            "display_name": "JavaScript (Node.js)",
            "language": "javascript",
            "name": "javascript",
        },
        language_info={
            "codemirror_mode": "javascript",
            "file_extension": ".js",
            "mimetype": "application/javascript",
            "name": "javascript",
            "pygments_lexer": "javascript",
            "version": "",
        },
        setup=textwrap.dedent(
            """\
            The cells are unexecuted and call `require`, so they need a CommonJS
            JavaScript kernel such as
            [IJavascript](https://github.com/n-riesco/ijavascript), with the package
            installed beside the notebook:

            ```console
            npm install yggdryl
            ```
            """
        ),
    ),
}


def site_url() -> str:
    """Return the published site root, read from the MkDocs configuration."""
    # Read rather than repeated here, so a downloaded notebook cannot point at a
    # site the documentation has since moved away from.
    configuration = (ROOT / "mkdocs.yml").read_text(encoding="utf-8")
    match = re.search(r"^site_url:\s*(\S+)", configuration, re.MULTILINE)
    return match.group(1).rstrip("/") + "/" if match else ""


def page_url(page: pathlib.Path) -> str:
    """Return the published address of a documentation page."""
    relative = page.relative_to(DOCS).with_suffix("").as_posix()
    directory = "" if relative == "index" else f"{relative}/"
    return f"{site_url()}{directory}"


def source(text: str) -> list[str]:
    """Split a cell body the way a notebook stores it: one entry per line."""
    return text.strip("\n").splitlines(keepends=True)


def markdown_cell(identity: str, text: str) -> dict:
    """Return one markdown cell."""
    return {"cell_type": "markdown", "id": identity, "metadata": {}, "source": source(text)}


def code_cell(identity: str, code: str) -> dict:
    """Return one unexecuted code cell."""
    return {
        "cell_type": "code",
        "execution_count": None,
        "id": identity,
        "metadata": {},
        "outputs": [],
        "source": source(code),
    }


def intro(page: pathlib.Path, kernel: Kernel, name: str, count: int) -> str:
    """Return the opening markdown cell: what this is, and what to install first."""
    tally = "The one" if count == 1 else f"All {count}"
    plural = "" if count == 1 else "s"
    # The extension pages are named after the language they document, where
    # `Python - Python` would read as a mistake rather than as a title.
    heading = name if name == kernel.title else f"{name} - {kernel.title}"
    return (
        f"# {heading}\n"
        "\n"
        f"{tally} {kernel.title} example{plural} from "
        f"[{page.relative_to(ROOT).as_posix()}]({page_url(page)}), in page order.\n"
        "\n"
        "Generated by `scripts/build_docs_notebooks.py` from the blocks that\n"
        "`scripts/check_docs_examples.py` compiles and runs, so every code cell below is\n"
        "an example that passed. An edit here lives until the next build overwrites it.\n"
        "\n"
        f"{kernel.setup}"
    )


def cells(page: pathlib.Path, kernel: Kernel, examples: list[Block]) -> list[dict]:
    """Return the cells of one notebook: an introduction, the sections, the examples."""
    found = headings(page.read_text(encoding="utf-8"))
    # The page heading already titles the notebook, so only the sections below it
    # earn a cell, and only where the section changes.
    section = found[0][1] if found else ""
    name = section.lstrip("#").strip() or slug(page)
    document = [markdown_cell("intro", intro(page, kernel, name, len(examples)))]
    for position, block in enumerate(examples):
        if block.section and block.section != section:
            section = block.section
            document.append(markdown_cell(f"section-{position}", section))
        document.append(code_cell(f"example-{block.index}", block.code))
    return document


def notebook(page: pathlib.Path, language: str, examples: list[Block]) -> str:
    """Render one page's examples in one language as notebook JSON."""
    kernel = KERNELS[language]
    document = {
        "cells": cells(page, kernel, examples),
        "metadata": {
            "kernelspec": dict(kernel.kernelspec),
            "language_info": dict(kernel.language_info),
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    # Sorted keys and a fixed indent are what make a rebuild byte-identical, which
    # is the whole reason a generated file can be committed.
    return json.dumps(document, ensure_ascii=False, indent=1, sort_keys=True) + "\n"


def examples_of(page: pathlib.Path, language: str) -> list[Block]:
    """Return the blocks of one language on a page that the checker runs."""
    return [
        block
        for block in blocks(page)
        if block.language == language and runnable(language, block.flags)
    ]


def links(page: pathlib.Path, produced: list[tuple[str, pathlib.Path]]) -> str:
    """Return the page section that offers this page's notebooks as downloads."""
    offers = ",\n".join(
        f"[{KERNELS[language].title}]"
        f"({os.path.relpath(path, page.parent).replace(os.sep, '/')})"
        "{ download }"
        for language, path in produced
    )
    return (
        f"{START}\n"
        "\n"
        "## Notebooks\n"
        "\n"
        "Every example on this page, as a notebook generated from these blocks and\n"
        "shipped unexecuted:\n"
        f"{offers}.\n"
        "\n"
        f"{END}\n"
    )


def relink(text: str, page: pathlib.Path, produced: list[tuple[str, pathlib.Path]]) -> str:
    """Return the page with its notebook section rewritten, added, or removed."""
    # Every marker pair goes, not just the first, so a page that was copied from
    # another one settles back to a single section instead of accumulating.
    while (start := text.find(START)) != -1:
        end = text.find(END, start)
        if end == -1:
            raise ValueError(f"{page.relative_to(ROOT)} opens a notebook section it never closes")
        text = text[:start] + text[end + len(END) :]
    body = text.rstrip("\n")
    return f"{body}\n" if not produced else f"{body}\n\n{links(page, produced)}"


def newline_of(path: pathlib.Path) -> str:
    """Return the line ending a file already uses, so a rewrite keeps its style."""
    return "\r\n" if b"\r\n" in path.read_bytes() else "\n"


def store(path: pathlib.Path, content: str, *, write: bool) -> str | None:
    """Write a file when its content changed, or report the change when checking."""
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return None
    if not write:
        state = "is out of date" if current is not None else "is missing"
        return f"{path.relative_to(ROOT).as_posix()} {state}"
    path.parent.mkdir(parents=True, exist_ok=True)
    newline = newline_of(path) if path.exists() else "\n"
    path.write_text(content, encoding="utf-8", newline=newline)
    return None


def build(pages, *, write: bool = True) -> tuple[int, list[str]]:
    """Regenerate every notebook and page link, returning the count and what is wrong."""
    wanted: dict[pathlib.Path, str] = {}
    problems: list[str] = []

    for page in sorted(pages):
        produced: list[tuple[str, pathlib.Path]] = []
        for language in LANGUAGES:
            examples = examples_of(page, language)
            if not examples:
                continue
            path = NOTEBOOKS / f"{slug(page)}-{language}.ipynb"
            wanted[path] = notebook(page, language, examples)
            produced.append((language, path))

        text = page.read_text(encoding="utf-8")
        if store(page, relink(text, page, produced), write=write):
            problems.append(f"{page.relative_to(ROOT).as_posix()} has a stale notebook section")

    for path, content in sorted(wanted.items()):
        problem = store(path, content, write=write)
        if problem:
            problems.append(problem)

    existing = sorted(NOTEBOOKS.glob("*.ipynb")) if NOTEBOOKS.exists() else []
    for path in existing:
        if path in wanted:
            continue
        # A page that lost its examples, or was renamed, leaves a notebook behind
        # that no longer matches anything the checker runs.
        if write:
            path.unlink()
        else:
            problems.append(f"{path.relative_to(ROOT).as_posix()} belongs to no page")

    return len(wanted), problems


def main() -> int:
    """Regenerate the notebooks, or report what a regeneration would change."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="report what is stale instead of writing it"
    )
    arguments = parser.parse_args()

    pages = sorted(DOCS.rglob("*.md"))
    count, problems = build(pages, write=not arguments.check)
    verb = "checked" if arguments.check else "generated"
    print(f"notebooks: {count} {verb} from {len(pages)} pages")
    for problem in problems:
        print(f"  {problem}")
    return 1 if problems else 0


if __name__ == "__main__":
    sys.exit(main())
