"""Regenerate `yggdryl::internals` from the modules that declare one.

A test lives in `rust/tests/` and reaches the crate through `yggdryl::`. What a
caller cannot reach - a signing step, a format reader, a canonical rewrite - is
reached through `yggdryl::internals::<module path>`, which exists only under the
non-default `internals` feature.

A module opts in by declaring its own, next to what it owns:

    #[cfg(feature = "internals")]
    #[doc(hidden)]
    pub mod internals {
        //! What `rust/tests/<path>.rs` pins and a caller cannot reach.
        pub use super::{canonicalize, read_at};
    }

This script collects every such module and writes the crate-level re-export, so
no two workers edit one file to add theirs.

Usage:
    python scripts/generate_internals.py            # rewrite lib.rs
    python scripts/generate_internals.py --check    # fail if it is stale
"""

from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "rust" / "src"
LIB = SRC / "lib.rs"
DECLARATION = re.compile(r'^#\[cfg\(feature = "internals"\)\]\n#\[doc\(hidden\)\]\npub mod internals \{', re.M)

START = "// GENERATED by scripts/generate_internals.py - do not edit by hand.\n"
END = "// END GENERATED\n"


def module_path(path: pathlib.Path) -> str:
    """Return the crate path of the module a source file is."""
    relative = path.relative_to(SRC)
    parts = list(relative.parts)
    if parts[-1] in {"mod.rs", "lib.rs"}:
        parts.pop()
    else:
        parts[-1] = parts[-1].removesuffix(".rs")
    return "::".join(parts)


def guards(path: pathlib.Path) -> list[str]:
    """Return the cfg attributes the crate declares this module behind: those on
    every `mod` declaration from `lib.rs` down to the file's own."""
    parts = module_path(path).split("::")
    found: list[str] = []
    declaring = LIB
    for depth, name in enumerate(parts):
        lines = declaring.read_text(encoding="utf-8").splitlines()
        for index, line in enumerate(lines):
            if not re.match(rf"^(?:pub(?:\([a-z]+\))? )?mod {name};$", line):
                continue
            own: list[str] = []
            look = index - 1
            while look >= 0 and lines[look].startswith("#["):
                if lines[look].startswith("#[cfg"):
                    own.append(lines[look])
                look -= 1
            found.extend(reversed(own))
            break
        folder = SRC.joinpath(*parts[: depth + 1])
        declaring = folder / "mod.rs"
        if not declaring.exists():
            declaring = folder.with_suffix(".rs")
    return found


def block() -> str:
    owners = []
    for path in sorted(SRC.rglob("*.rs")):
        if path == LIB:
            continue
        if DECLARATION.search(path.read_text(encoding="utf-8")):
            owners.append(path)

    body = []
    for path in owners:
        crate_path = module_path(path)
        alias = crate_path.replace("::", "_")
        for cfg in guards(path):
            body.append(f"    {cfg}")
        body.append(f"    pub use crate::{crate_path}::internals as {alias};")

    return (
        START
        + "/// What the test suite pins and a caller cannot reach.\n"
        + "///\n"
        + "/// Every test lives in `rust/tests/` and reaches the crate through\n"
        + "/// `yggdryl::`. The handful that pin something no caller can name reach it\n"
        + "/// here instead, under a feature no published build turns on. This is not\n"
        + "/// API: it carries no stability promise, and an item is `pub` only because\n"
        + "/// its own module is unreachable without the feature.\n"
        + '#[cfg(feature = "internals")]\n'
        + "#[doc(hidden)]\n"
        + "pub mod internals {\n"
        + ("\n".join(body) + "\n" if body else "")
        + "}\n"
        + END
    )


def main() -> int:
    text = LIB.read_text(encoding="utf-8")
    generated = block()
    if START in text:
        start = text.index(START)
        end = text.index(END, start) + len(END)
        current = text[start:end]
        updated = text[:start] + generated + text[end:]
    else:
        anchor = "\n#[cfg(test)]\nmod tests {"
        if anchor not in text:
            print("lib.rs: no anchor to place the generated block before", file=sys.stderr)
            return 1
        current = ""
        updated = text.replace(anchor, "\n" + generated + anchor)

    if "--check" in sys.argv:
        if current != generated:
            print("yggdryl::internals is stale; run scripts/generate_internals.py", file=sys.stderr)
            return 1
        print("yggdryl::internals is current")
        return 0

    LIB.write_text(updated, encoding="utf-8")
    print(f"lib.rs: internals re-exports {generated.count('pub use')} module(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
