"""Allocation-conscious types, storage, media, and protocols.

The package is laid out the way the Rust core is: one module per type at the
root, one module or package per implementation, and a package only where its
implementations share something - `media/` for what every record medium has in
common, `text/` for the plain-text medium and the machinery the structured
codecs ride on, `coding/`, `holder/`, `charset/`, `enums/`. Every type is
re-exported here, as the crate re-exports each of its root files.

The native core reports what it does through `logging`, under this package's
own logger: `yggdryl.iceberg.table` and its siblings are the Rust module
paths the work happens in, so `logging.getLogger("yggdryl")` is the one switch.
Debug is an operation starting, info is one done and carries the counts a
monitor watches - a table opened, a scan planned and what its filters pruned,
a snapshot's rows and files, a commit and the version it landed. Nothing is
reported per row, per batch, or per file. A level changed after import reaches
the bridge through `refresh_logging`.
"""

from . import (
    arrow,
    avro,
    charset,
    codes,
    coding,
    enums,
    expression,
    fix,
    floating,
    geospatial,
    gzip,
    holder,
    iceberg,
    integer,
    json,
    media,
    nested,
    temporal,
    text,
    toml,
    txhash,
    uri,
    xxhash,
    yaml,
    zlib,
    zstd,
)
from ._native import (
    AVRO_MAX_SCHEMA_DEPTH,
    DEFAULT_FETCH_BYTE_SIZE,
    DEFAULT_RECORD_BATCH_ROW_SIZE,
    DEFAULT_STREAM_BATCH_SIZE,
    IPC_DICTIONARY_IDS_KEY,
    NULL_PARTITION,
    ArrowCastPlan,
    ArrowScalar,
    BytesParameters,
    DataType,
    Field,
    FieldPath,
    ProtocolField,
    PythonMetadata,
    StringEnum,
    StringParameters,
    Timezone,
    __version__,
    combined,
    refresh_logging,
)
from .expression import (
    Bound,
    Bounds,
    BoundSelector,
    Expression,
    Filter,
    Plan,
    Records,
    Selector,
    Term,
)
from .holder import IOBase, IOCursor
from .media import Avro, Ipc, Media, Parquet, RecordOptions, Text
from .mediatype import MediaType
from .mimetype import MimeType
from .text import TextEntries, TextEntry, TextLine, TextLines, TextOptions
from .uri import Arn, Parameters, Uri, Url, Urn

from ._classes import field
from ._typing import TypedDataType, TypedField
from .bytes import (
    BytesField,
    binary,
    binary_view,
    bytes,
    fixed_size_binary,
    large_binary,
    large_binary_view,
    sized_binary,
)
from .codes import (
    BloombergCodeField,
    CfiCodeField,
    FIGICodeField,
    CountryField,
    CurrencyField,
    CusipCodeField,
    IsinCodeField,
    MicCodeField,
    SedolCodeField,
    SideField,
    StateField,
    TimeInForceField,
    bloomberg,
    cfi,
    country,
    currency,
    figi,
    cusip,
    isin,
    mic,
    sedol,
    side,
    state,
    timeinforce,
)
from .decimal import (
    Decimal32Field,
    Decimal64Field,
    Decimal128Field,
    Decimal256Field,
    DecimalField,
    decimal,
    decimal32,
    decimal64,
    decimal128,
    decimal256,
)
from .floating import (
    Float16Field,
    Float32Field,
    Float64Field,
    float16,
    float32,
    float64,
)
from .geospatial import (
    GeographyField,
    GeometryField,
    UuidField,
    VariantField,
    geography,
    geometry,
    uuid,
    variant,
)
from .integer import (
    Int8Field,
    Int16Field,
    Int32Field,
    Int64Field,
    UInt8Field,
    UInt16Field,
    UInt32Field,
    UInt64Field,
    int8,
    int16,
    int32,
    int64,
    uint8,
    uint16,
    uint32,
    uint64,
)
from .nested import (
    DenseUnionField,
    DictionaryField,
    FixedSizeListField,
    LargeListField,
    LargeListViewField,
    ListField,
    ListViewField,
    MapField,
    RunEndEncodedField,
    StructField,
    UnionField,
    dense_union,
    dictionary,
    fixed_size_list,
    large_list,
    large_list_view,
    list,
    list_view,
    map,
    map_of,
    run_end_encoded,
    struct,
    union,
)
from .boolean import BooleanField, NullField, boolean, null
from .scalar import Scalar, scalar
from .serie import (
    FixedSizeListSerie,
    LargeListSerie,
    LargeListViewSerie,
    ListSerie,
    ListViewSerie,
    MapSerie,
    Serie,
    SerieReader,
    StructSerie,
)
from .string import (
    StringField,
    ascii,
    ascii_view,
    cp1252,
    cp1252_view,
    fixed_ascii,
    fixed_cp1252,
    fixed_utf8,
    large_ascii,
    large_ascii_view,
    large_cp1252,
    large_cp1252_view,
    large_utf8,
    large_utf8_view,
    sized_ascii,
    sized_cp1252,
    sized_utf8,
    string,
    utf8,
    utf8_view,
)
from .temporal import (
    Date32Field,
    Date64Field,
    Duration32Field,
    Duration64Field,
    IntervalField,
    Time32Field,
    Time64Field,
    TimeField,
    DateTime64Field,
    date32,
    date64,
    duration32,
    duration64,
    interval,
    time,
    time32,
    time64,
    datetime64,
)
from .mediatype import MediaTypeField, mediatype
from .mimetype import MimeTypeField, mimetype
from .timezone import TimezoneField, timezone
from .urn import UrnField, urn
from .url import UrlField, url
from .version import Version, VersionField, version

__all__ = [
    "AVRO_MAX_SCHEMA_DEPTH",
    "Arn",
    "ArrowCastPlan",
    "ArrowScalar",
    "Avro",
    "BloombergCodeField",
    "BooleanField",
    "Bound",
    "BoundSelector",
    "Bounds",
    "BytesField",
    "BytesParameters",
    "CfiCodeField",
    "CountryField",
    "CurrencyField",
    "CusipCodeField",
    "DEFAULT_FETCH_BYTE_SIZE",
    "DEFAULT_RECORD_BATCH_ROW_SIZE",
    "DEFAULT_STREAM_BATCH_SIZE",
    "DataType",
    "Date32Field",
    "Date64Field",
    "DateTime64Field",
    "Decimal128Field",
    "Decimal256Field",
    "Decimal32Field",
    "Decimal64Field",
    "DecimalField",
    "DenseUnionField",
    "DictionaryField",
    "Duration32Field",
    "Duration64Field",
    "Expression",
    "FIGICodeField",
    "Field",
    "FieldPath",
    "Filter",
    "FixedSizeListField",
    "FixedSizeListSerie",
    "Float16Field",
    "Float32Field",
    "Float64Field",
    "GeographyField",
    "GeometryField",
    "IOBase",
    "IOCursor",
    "IPC_DICTIONARY_IDS_KEY",
    "Int16Field",
    "Int32Field",
    "Int64Field",
    "Int8Field",
    "IntervalField",
    "Ipc",
    "IsinCodeField",
    "LargeListField",
    "LargeListSerie",
    "LargeListViewField",
    "LargeListViewSerie",
    "ListField",
    "ListSerie",
    "ListViewField",
    "ListViewSerie",
    "MapField",
    "MapSerie",
    "Media",
    "MediaType",
    "MediaTypeField",
    "MicCodeField",
    "MimeType",
    "MimeTypeField",
    "NULL_PARTITION",
    "NullField",
    "Parameters",
    "Parquet",
    "Plan",
    "ProtocolField",
    "PythonMetadata",
    "RecordOptions",
    "Records",
    "RunEndEncodedField",
    "Scalar",
    "SedolCodeField",
    "Selector",
    "Serie",
    "SerieReader",
    "SideField",
    "StateField",
    "StringEnum",
    "StringField",
    "StringParameters",
    "StructField",
    "StructSerie",
    "Term",
    "Text",
    "TextEntries",
    "TextEntry",
    "TextLine",
    "TextLines",
    "TextOptions",
    "Time32Field",
    "Time64Field",
    "TimeField",
    "TimeInForceField",
    "Timezone",
    "TimezoneField",
    "TypedDataType",
    "TypedField",
    "UInt16Field",
    "UInt32Field",
    "UInt64Field",
    "UInt8Field",
    "UnionField",
    "Uri",
    "Url",
    "UrlField",
    "Urn",
    "UrnField",
    "UuidField",
    "VariantField",
    "Version",
    "VersionField",
    "__version__",
    "arrow",
    "ascii",
    "ascii_view",
    "avro",
    "binary",
    "binary_view",
    "bloomberg",
    "boolean",
    "bytes",
    "cfi",
    "charset",
    "codes",
    "coding",
    "combined",
    "country",
    "cp1252",
    "cp1252_view",
    "currency",
    "cusip",
    "date32",
    "date64",
    "datetime64",
    "decimal",
    "decimal128",
    "decimal256",
    "decimal32",
    "decimal64",
    "dense_union",
    "dictionary",
    "duration32",
    "duration64",
    "enums",
    "expression",
    "field",
    "figi",
    "fix",
    "fixed_ascii",
    "fixed_cp1252",
    "fixed_size_binary",
    "fixed_size_list",
    "fixed_utf8",
    "float16",
    "float32",
    "float64",
    "floating",
    "geography",
    "geometry",
    "geospatial",
    "gzip",
    "holder",
    "iceberg",
    "int16",
    "int32",
    "int64",
    "int8",
    "integer",
    "interval",
    "isin",
    "json",
    "large_ascii",
    "large_ascii_view",
    "large_binary",
    "large_binary_view",
    "large_cp1252",
    "large_cp1252_view",
    "large_list",
    "large_list_view",
    "large_utf8",
    "large_utf8_view",
    "list",
    "list_view",
    "map",
    "map_of",
    "media",
    "mediatype",
    "mic",
    "mimetype",
    "nested",
    "null",
    "refresh_logging",
    "run_end_encoded",
    "scalar",
    "sedol",
    "side",
    "sized_ascii",
    "sized_binary",
    "sized_cp1252",
    "sized_utf8",
    "state",
    "string",
    "struct",
    "temporal",
    "text",
    "time",
    "time32",
    "time64",
    "timeinforce",
    "timezone",
    "toml",
    "txhash",
    "uint16",
    "uint32",
    "uint64",
    "uint8",
    "union",
    "uri",
    "url",
    "urn",
    "utf8",
    "utf8_view",
    "uuid",
    "variant",
    "version",
    "xxhash",
    "yaml",
    "zlib",
    "zstd",
]
