from __future__ import annotations

from collections.abc import Iterable, Iterator, Mapping
from os import PathLike
from typing import Any, ClassVar, Literal, SupportsIndex, overload

import pyarrow  # type: ignore[import-untyped]

__version__: str
CompatibilityScheme = Literal["arrow", "spark", "polars", "pandas", "iceberg"]

class MimeType:
    OCTET_STREAM: ClassVar[MimeType]
    JSON: ClassVar[MimeType]
    JSON_LINES: ClassVar[MimeType]
    YAML: ClassVar[MimeType]
    TOML: ClassVar[MimeType]
    CSV: ClassVar[MimeType]
    TSV: ClassVar[MimeType]
    PARQUET: ClassVar[MimeType]
    ARROW_FILE: ClassVar[MimeType]
    ARROW_STREAM: ClassVar[MimeType]
    AVRO: ClassVar[MimeType]
    ORC: ClassVar[MimeType]
    PLAIN_TEXT: ClassVar[MimeType]
    MARKDOWN: ClassVar[MimeType]
    HTML: ClassVar[MimeType]
    CSS: ClassVar[MimeType]
    JAVASCRIPT: ClassVar[MimeType]
    XML: ClassVar[MimeType]
    PDF: ClassVar[MimeType]
    CBOR: ClassVar[MimeType]
    MESSAGE_PACK: ClassVar[MimeType]
    PROTOBUF: ClassVar[MimeType]
    SQLITE3: ClassVar[MimeType]
    PNG: ClassVar[MimeType]
    JPEG: ClassVar[MimeType]
    GIF: ClassVar[MimeType]
    WEBP: ClassVar[MimeType]
    SVG: ClassVar[MimeType]
    MP3: ClassVar[MimeType]
    WAV: ClassVar[MimeType]
    OGG: ClassVar[MimeType]
    FLAC: ClassVar[MimeType]
    MP4: ClassVar[MimeType]
    WEBM: ClassVar[MimeType]
    WOFF: ClassVar[MimeType]
    WOFF2: ClassVar[MimeType]
    TTF: ClassVar[MimeType]
    OTF: ClassVar[MimeType]
    XLS: ClassVar[MimeType]
    XLSX: ClassVar[MimeType]
    ODS: ClassVar[MimeType]
    DOC: ClassVar[MimeType]
    DOCX: ClassVar[MimeType]
    GZIP: ClassVar[MimeType]
    ZSTD: ClassVar[MimeType]
    BROTLI: ClassVar[MimeType]
    ZLIB: ClassVar[MimeType]
    COMPRESS: ClassVar[MimeType]
    BZIP2: ClassVar[MimeType]
    XZ: ClassVar[MimeType]
    LZ4: ClassVar[MimeType]
    SNAPPY: ClassVar[MimeType]
    ZIP: ClassVar[MimeType]
    SEVEN_ZIP: ClassVar[MimeType]
    RAR: ClassVar[MimeType]
    TAR: ClassVar[MimeType]
    def __init__(self, value: MimeType | str | None = None) -> None: ...
    @staticmethod
    def from_value(value: MimeType | str) -> MimeType: ...
    @staticmethod
    def from_str(value: str) -> MimeType: ...
    @staticmethod
    def from_extension(value: str) -> MimeType: ...
    @staticmethod
    def from_path(value: str | PathLike[str]) -> MimeType: ...
    @staticmethod
    def from_content_type(value: str) -> MimeType: ...
    @staticmethod
    def from_content_coding(value: str) -> MimeType: ...
    @staticmethod
    def from_json(value: str) -> MimeType: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    @property
    def top_level(self) -> str: ...
    @property
    def subtype(self) -> str: ...
    @property
    def structured_suffix(self) -> str | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def content_coding(
        self,
    ) -> Literal["gzip", "compress", "deflate", "br", "zstd"] | None: ...
    @property
    def format(self) -> Literal["json", "json_lines", "yaml", "toml"] | None: ...
    def is_known(self) -> bool: ...
    def is_application(self) -> bool: ...
    def is_audio(self) -> bool: ...
    def is_font(self) -> bool: ...
    def is_haptics(self) -> bool: ...
    def is_image(self) -> bool: ...
    def is_message(self) -> bool: ...
    def is_model(self) -> bool: ...
    def is_multipart(self) -> bool: ...
    def is_text(self) -> bool: ...
    def is_video(self) -> bool: ...
    def is_textual(self) -> bool: ...
    def is_structured(self) -> bool: ...
    def is_tabular(self) -> bool: ...
    def is_encoding(self) -> bool: ...
    def is_archive(self) -> bool: ...
    def is_binary(self) -> bool: ...
    def stable_hash(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: MimeType, /) -> bool: ...
    def __le__(self, other: MimeType, /) -> bool: ...
    def __gt__(self, other: MimeType, /) -> bool: ...
    def __ge__(self, other: MimeType, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> MimeType: ...
    def __deepcopy__(self, memo: Any) -> MimeType: ...

class MediaType:
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __init__(self, value: MediaType | MimeType | str | None = None) -> None: ...
    @staticmethod
    def from_value(value: MediaType | MimeType | str) -> MediaType: ...
    @staticmethod
    def from_str(value: str) -> MediaType: ...
    @staticmethod
    def from_parts(
        base: MimeType | str, encodings: Iterable[MimeType | str]
    ) -> MediaType: ...
    @staticmethod
    def from_extension(value: str) -> MediaType: ...
    @staticmethod
    def from_extensions(values: Iterable[str]) -> MediaType: ...
    @staticmethod
    def from_file_name(value: str) -> MediaType: ...
    @staticmethod
    def from_path(value: str | PathLike[str]) -> MediaType: ...
    @staticmethod
    def from_content_headers(
        content_type: str | None = None, content_encoding: str | None = None
    ) -> MediaType: ...
    @staticmethod
    def from_json(value: str) -> MediaType: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    @property
    def base(self) -> MimeType: ...
    @property
    def encodings(self) -> tuple[MimeType, ...]: ...
    @property
    def encoding(self) -> MimeType | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def extensions(self) -> list[str]: ...
    def set_base(self, value: MimeType | str) -> None: ...
    def set_encodings(self, values: Iterable[MimeType | str]) -> None: ...
    def push_encoding(self, value: MimeType | str) -> None: ...
    def clear_encodings(self) -> bool: ...
    def is_encoded(self) -> bool: ...
    def is_application(self) -> bool: ...
    def is_audio(self) -> bool: ...
    def is_font(self) -> bool: ...
    def is_haptics(self) -> bool: ...
    def is_image(self) -> bool: ...
    def is_message(self) -> bool: ...
    def is_model(self) -> bool: ...
    def is_multipart(self) -> bool: ...
    def is_text(self) -> bool: ...
    def is_video(self) -> bool: ...
    def is_textual(self) -> bool: ...
    def is_structured(self) -> bool: ...
    def is_tabular(self) -> bool: ...
    def is_encoding(self) -> bool: ...
    def is_archive(self) -> bool: ...
    def is_binary(self) -> bool: ...
    def stable_hash(self) -> int: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[MimeType]: ...
    def __getitem__(self, index: int, /) -> MimeType: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: MediaType, /) -> bool: ...
    def __le__(self, other: MediaType, /) -> bool: ...
    def __gt__(self, other: MediaType, /) -> bool: ...
    def __ge__(self, other: MediaType, /) -> bool: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> MediaType: ...
    def __deepcopy__(self, memo: Any) -> MediaType: ...

def _codec_infer(data: bytes | bytearray | memoryview) -> str: ...
def _codec_infer_path(value: str) -> str: ...
def _codec_infer_text(data: str) -> str: ...
def _codec_normalize_format(value: str) -> str: ...
def _codec_encode(value: object, format: str) -> bytes: ...
def _codec_encode_writer(
    value: object, destination: object, format: str
) -> None: ...
def _codec_encode_path(
    value: object,
    destination: str | PathLike[str] | PathLike[bytes],
    format: str,
) -> None: ...
def _codec_decode(data: bytes | bytearray | memoryview, format: str) -> object: ...
def _codec_decode_inferred(data: bytes | bytearray | memoryview) -> object: ...
def _codec_decode_inferred_text(data: str) -> object: ...
def _codec_decode_text(data: str, format: str) -> object: ...
def _codec_decode_reader(source: object, format: str) -> object: ...
def _codec_encode_all(values: Iterable[object], format: str) -> bytes: ...
def _codec_encode_all_writer(
    values: Iterable[object], destination: object, format: str
) -> None: ...
def _codec_decode_all(
    data: bytes | bytearray | memoryview, format: str
) -> list[object]: ...
def _codec_decode_all_text(data: str, format: str) -> list[object]: ...
def _codec_decode_all_reader(source: object, format: str) -> list[object]: ...

class DataType:
    def __init__(self, value: object) -> None: ...
    @staticmethod
    def from_value(value: object) -> DataType: ...
    @staticmethod
    def _simple(kind: str) -> DataType: ...
    @staticmethod
    def _temporal(
        kind: str, unit: str, timezone: str | None = None
    ) -> DataType: ...
    @staticmethod
    def _fixed_size_binary(byte_width: int) -> DataType: ...
    @staticmethod
    def _decimal(
        kind: str,
        precision: SupportsIndex | str,
        scale: SupportsIndex | str = 0,
    ) -> DataType: ...
    @staticmethod
    def _list(kind: str, item: Field, length: int | None = None) -> DataType: ...
    @staticmethod
    def _union(fields: Iterable[tuple[int, Field]], mode: str) -> DataType: ...
    @staticmethod
    def variant(fields: Iterable[Field]) -> DataType: ...
    @staticmethod
    def _dictionary(key: object, value: object) -> DataType: ...
    def _dictionary_value_type(self) -> DataType: ...
    @staticmethod
    def _map(entries: Field, keys_sorted: bool) -> DataType: ...
    @staticmethod
    def _run_end_encoded(run_ends: Field, values: Field) -> DataType: ...
    @staticmethod
    def time(unit: str) -> DataType: ...
    @staticmethod
    def decimal(
        precision: SupportsIndex | str, scale: SupportsIndex | str = 0
    ) -> DataType: ...
    @staticmethod
    def from_pyhint(hint: object) -> DataType: ...
    @staticmethod
    def from_str(value: str) -> DataType: ...
    @staticmethod
    def from_arrow(value: Any) -> DataType: ...
    @staticmethod
    def from_fields(fields: Iterable[Field]) -> DataType: ...
    @staticmethod
    def from_json(value: str) -> DataType: ...
    def to_arrow(self) -> Any: ...
    def default_pyvalue(self) -> object: ...
    def default_pyhint(self) -> object: ...
    def default_arrow_scalar(self) -> pyarrow.Scalar: ...
    def to_scheme_compat(self, target: CompatibilityScheme) -> DataType: ...
    def arrow_scalar(
        self, value: object, *, safe: bool = True
    ) -> pyarrow.Scalar: ...
    def cast_arrow_array(
        self, value: pyarrow.Array, *, safe: bool = True
    ) -> pyarrow.Array: ...
    def cast_arrow_batch(
        self, value: pyarrow.RecordBatch, *, safe: bool = True
    ) -> pyarrow.RecordBatch: ...
    def into_arrow(self) -> Any: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def id(self) -> str: ...
    @property
    def is_nested(self) -> bool: ...
    def _time_unit(self) -> str | None: ...
    def _timezone(self) -> str | None: ...
    def _fixed_size_list_length(self) -> int | None: ...
    def equals(self, other: DataType, with_metadata: bool = True) -> bool: ...
    def show_diffs(
        self, other: DataType, with_metadata: bool = True
    ) -> Iterator[str]: ...
    def show_diff(self, other: DataType, with_metadata: bool = True) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Field]: ...
    @overload
    def __getitem__(self, key: int, /) -> Field: ...
    @overload
    def __getitem__(self, key: str, /) -> Field: ...
    def __contains__(self, value: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: DataType, /) -> bool: ...
    def __le__(self, other: DataType, /) -> bool: ...
    def __gt__(self, other: DataType, /) -> bool: ...
    def __ge__(self, other: DataType, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> DataType: ...
    def __deepcopy__(self, memo: Any) -> DataType: ...

class ProtocolMetadata:
    # A live view of mutable field metadata cannot promise a stable hash.
    __hash__: ClassVar[None]  # type: ignore[assignment]
    @property
    def scheme(self) -> str: ...
    @property
    def prefix(self) -> str: ...
    def key(self, name: str) -> str: ...
    def get(self, name: str, default: object = None, /) -> object: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[str]: ...
    def items(self) -> Iterator[tuple[str, str]]: ...
    def update(
        self,
        values: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
        /,
        **kwargs: str,
    ) -> None: ...
    def clear(self) -> None: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, name: object, /) -> bool: ...
    def __getitem__(self, name: str, /) -> str: ...
    def __setitem__(self, name: str, value: str, /) -> None: ...
    def __delitem__(self, name: str, /) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    # Two views are equal when they hold the same properties, whichever field
    # and protocol each of them reads through.
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

class Field:
    def __init__(
        self,
        name: str,
        data_type: object,
        nullable: bool = True,
        metadata: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
    ) -> None: ...
    @staticmethod
    def from_value(value: object) -> Field: ...
    @staticmethod
    def from_pyhint(
        name: str,
        hint: object,
        metadata: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
    ) -> Field: ...
    @staticmethod
    def from_str(value: str) -> Field: ...
    @staticmethod
    def from_arrow(value: Any) -> Field: ...
    @staticmethod
    def _record_root_from_arrow_schema(value: Any, name: str) -> Field: ...
    def _record_root_to_arrow_transport_schema(self) -> Any: ...
    @staticmethod
    def from_json(value: str) -> Field: ...
    def to_arrow(self) -> Any: ...
    def default_pyvalue(self) -> object: ...
    def default_pyhint(self) -> object: ...
    def default_arrow_scalar(self) -> pyarrow.Scalar: ...
    def to_scheme_compat(self, target: CompatibilityScheme) -> Field: ...
    def arrow_scalar(
        self, value: object, *, safe: bool = True
    ) -> pyarrow.Scalar: ...
    def cast_arrow_array(
        self, value: pyarrow.Array, *, safe: bool = True
    ) -> pyarrow.Array: ...
    def cast_arrow_batch(
        self, value: pyarrow.RecordBatch, *, safe: bool = True
    ) -> pyarrow.RecordBatch: ...
    def into_arrow(self) -> Any: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def data_type(self) -> DataType: ...
    @property
    def nullable(self) -> bool: ...
    @property
    def parquet_field_id(self) -> int | None: ...
    @property
    def dictionary_id(self) -> int | None: ...
    @property
    def dictionary_is_ordered(self) -> bool | None: ...
    @property
    def alias(self) -> str | None: ...
    @property
    def catalog_name(self) -> str | None: ...
    @property
    def schema_name(self) -> str | None: ...
    @property
    def table_name(self) -> str | None: ...
    @property
    def location(self) -> Url | None: ...
    @property
    def accept(self) -> str | None: ...
    @property
    def accept_encoding(self) -> str | None: ...
    @property
    def accept_language(self) -> str | None: ...
    @property
    def accept_ranges(self) -> str | None: ...
    @property
    def cache_control(self) -> str | None: ...
    @property
    def content_disposition(self) -> str | None: ...
    @property
    def content_encoding(self) -> str | None: ...
    @property
    def content_language(self) -> str | None: ...
    @property
    def content_length(self) -> int | None: ...
    @property
    def content_location(self) -> str | None: ...
    @property
    def content_range(self) -> str | None: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def mime_type(self) -> MimeType: ...
    @property
    def media_type(self) -> MediaType: ...
    @property
    def etag(self) -> str | None: ...
    @property
    def expires(self) -> str | None: ...
    @property
    def last_modified(self) -> str | None: ...
    @property
    def http_location(self) -> Url | None: ...
    @property
    def range(self) -> str | None: ...
    @property
    def vary(self) -> str | None: ...
    def set_dictionary_options(self, id: int, is_ordered: bool) -> None: ...
    def set_parquet_field_id(self, id: SupportsIndex) -> None: ...
    def remove_parquet_field_id(self) -> int | None: ...
    def set_alias(self, value: str) -> None: ...
    def remove_alias(self) -> str | None: ...
    def set_catalog_name(self, value: str) -> None: ...
    def remove_catalog_name(self) -> str | None: ...
    def set_schema_name(self, value: str) -> None: ...
    def remove_schema_name(self) -> str | None: ...
    def set_table_name(self, value: str) -> None: ...
    def remove_table_name(self) -> str | None: ...
    def set_location(self, value: Url | Uri | str | PathLike[str]) -> None: ...
    def remove_location(self) -> Url | None: ...
    def set_accept(self, value: str) -> None: ...
    def remove_accept(self) -> str | None: ...
    def set_accept_encoding(self, value: str) -> None: ...
    def remove_accept_encoding(self) -> str | None: ...
    def set_accept_language(self, value: str) -> None: ...
    def remove_accept_language(self) -> str | None: ...
    def set_accept_ranges(self, value: str) -> None: ...
    def remove_accept_ranges(self) -> str | None: ...
    def set_cache_control(self, value: str) -> None: ...
    def remove_cache_control(self) -> str | None: ...
    def set_content_disposition(self, value: str) -> None: ...
    def remove_content_disposition(self) -> str | None: ...
    def set_content_encoding(self, value: str) -> None: ...
    def remove_content_encoding(self) -> str | None: ...
    def set_content_language(self, value: str) -> None: ...
    def remove_content_language(self) -> str | None: ...
    def set_content_length(self, value: SupportsIndex) -> None: ...
    def remove_content_length(self) -> int | None: ...
    def set_content_location(self, value: str) -> None: ...
    def remove_content_location(self) -> str | None: ...
    def set_content_range(self, value: str) -> None: ...
    def remove_content_range(self) -> str | None: ...
    def set_content_type(self, value: str) -> None: ...
    def remove_content_type(self) -> str | None: ...
    def set_mime_type(self, value: MimeType | str) -> None: ...
    def remove_mime_type(self) -> MimeType | None: ...
    def set_media_type(self, value: MediaType | MimeType | str) -> None: ...
    def remove_media_type(self) -> MediaType | None: ...
    def set_etag(self, value: str) -> None: ...
    def remove_etag(self) -> str | None: ...
    def set_expires(self, value: str) -> None: ...
    def remove_expires(self) -> str | None: ...
    def set_last_modified(self, value: str) -> None: ...
    def remove_last_modified(self) -> str | None: ...
    def set_http_location(self, value: Url | Uri | str | PathLike[str]) -> None: ...
    def remove_http_location(self) -> Url | None: ...
    def set_range(self, value: str) -> None: ...
    def remove_range(self) -> str | None: ...
    def set_vary(self, value: str) -> None: ...
    def remove_vary(self) -> str | None: ...
    def get_property(self, scheme: str, name: str) -> str | None: ...
    def has_property(self, scheme: str, name: str) -> bool: ...
    def set_property(self, scheme: str, name: str, value: str) -> str | None: ...
    def remove_property(self, scheme: str, name: str) -> str | None: ...
    def property_iter(self, scheme: str) -> Iterator[tuple[str, str]]: ...
    def clear_properties(self, scheme: str) -> None: ...
    def protocol(self, scheme: str) -> ProtocolMetadata: ...
    # One named view per well-known protocol. ``https`` is deliberately absent:
    # it shares the canonical ``http:`` namespace, which ``http`` already reads.
    @property
    def http(self) -> ProtocolMetadata: ...
    @property
    def file(self) -> ProtocolMetadata: ...
    @property
    def urn(self) -> ProtocolMetadata: ...
    @property
    def postgres(self) -> ProtocolMetadata: ...
    @property
    def postgresql(self) -> ProtocolMetadata: ...
    @property
    def mysql(self) -> ProtocolMetadata: ...
    @property
    def arrow(self) -> ProtocolMetadata: ...
    @property
    def sql(self) -> ProtocolMetadata: ...
    @property
    def glue(self) -> ProtocolMetadata: ...
    @property
    def iceberg(self) -> ProtocolMetadata: ...
    @property
    def fix(self) -> ProtocolMetadata: ...
    @property
    def field(self) -> ProtocolMetadata: ...
    @property
    def dtype(self) -> ProtocolMetadata: ...
    @property
    def s3(self) -> ProtocolMetadata: ...
    @property
    def gs(self) -> ProtocolMetadata: ...
    @property
    def az(self) -> ProtocolMetadata: ...
    @property
    def spark(self) -> ProtocolMetadata: ...
    @property
    def polars(self) -> ProtocolMetadata: ...
    @property
    def pandas(self) -> ProtocolMetadata: ...
    @property
    def is_partition(self) -> bool: ...
    def set_partition(self, partition: bool) -> None: ...
    @property
    def partition_fields(self) -> list[Field]: ...
    @property
    def partition_field_names(self) -> list[str]: ...
    @property
    def partition_field_len(self) -> int: ...
    @property
    def has_partition_fields(self) -> bool: ...
    def only_partition_fields(self) -> Field: ...
    def without_partition_fields(self) -> Field: ...
    def with_partition_fields(self, names: Iterable[str]) -> Field: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __contains__(self, key: object, /) -> bool: ...
    def __getitem__(self, key: str, /) -> str: ...
    def __setitem__(self, key: str, value: str, /) -> None: ...
    def __delitem__(self, key: str, /) -> None: ...
    def get(self, key: str, default: object = None, /) -> object: ...
    def keys(self) -> Iterator[str]: ...
    def values(self) -> Iterator[str]: ...
    def items(self) -> Iterator[tuple[str, str]]: ...
    def update(
        self,
        values: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
        /,
        **kwargs: str,
    ) -> None: ...
    def clear(self) -> None: ...
    def equals(self, other: Field, with_metadata: bool = True) -> bool: ...
    def show_diffs(
        self, other: Field, with_metadata: bool = True
    ) -> Iterator[str]: ...
    def show_diff(self, other: Field, with_metadata: bool = True) -> str: ...
    # Internal records hook: published cached schema values become immutable.
    def _freeze(self) -> None: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Field, /) -> bool: ...
    def __le__(self, other: Field, /) -> bool: ...
    def __gt__(self, other: Field, /) -> bool: ...
    def __ge__(self, other: Field, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> Field: ...
    def __deepcopy__(self, memo: Any) -> Field: ...

class Uri:
    def __init__(self, value: Uri | Url | Urn | str | PathLike[str]) -> None: ...
    @staticmethod
    def from_value(value: Uri | Url | Urn | str | PathLike[str]) -> Uri: ...
    @staticmethod
    def from_str(value: str) -> Uri: ...
    @staticmethod
    def from_path(value: str | PathLike[str]) -> Uri: ...
    @staticmethod
    def from_json(value: str) -> Uri: ...
    def to_url(self) -> Url: ...
    def into_url(self) -> Url: ...
    def to_urn(self) -> Urn: ...
    def into_urn(self) -> Urn: ...
    def to_path(self) -> str: ...
    def into_path(self) -> str: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    def __fspath__(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str | None: ...
    @property
    def fragment(self) -> str | None: ...
    @property
    def path_segments(self) -> tuple[str, ...]: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def stem(self) -> str | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def extensions(self) -> tuple[str, ...]: ...
    @property
    def mime_type(self) -> MimeType: ...
    @property
    def media_type(self) -> MediaType: ...
    def set_file_name(self, value: str) -> None: ...
    def set_stem(self, value: str) -> None: ...
    def set_extension(self, value: str) -> None: ...
    def set_extensions(self, values: Iterable[str]) -> None: ...
    def remove_extension(self) -> bool: ...
    def clear_extensions(self) -> bool: ...
    def set_mime_type(self, value: MimeType | str) -> None: ...
    def set_media_type(self, value: MediaType | MimeType | str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, index: int, /) -> str: ...
    def __contains__(self, segment: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Uri, /) -> bool: ...
    def __le__(self, other: Uri, /) -> bool: ...
    def __gt__(self, other: Uri, /) -> bool: ...
    def __ge__(self, other: Uri, /) -> bool: ...
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> Uri: ...
    def __deepcopy__(self, memo: Any) -> Uri: ...

class Url:
    def __init__(self, value: Url | Uri | Urn | str | PathLike[str]) -> None: ...
    @staticmethod
    def from_value(value: Url | Uri | Urn | str | PathLike[str]) -> Url: ...
    @staticmethod
    def from_str(value: str) -> Url: ...
    @staticmethod
    def from_path(value: str | PathLike[str]) -> Url: ...
    @staticmethod
    def from_uri(value: Uri) -> Url: ...
    @staticmethod
    def from_json(value: str) -> Url: ...
    def to_uri(self) -> Uri: ...
    def into_uri(self) -> Uri: ...
    def to_path(self) -> str: ...
    def into_path(self) -> str: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    def __fspath__(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str | None: ...
    @property
    def fragment(self) -> str | None: ...
    @property
    def path_segments(self) -> tuple[str, ...]: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def stem(self) -> str | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def extensions(self) -> tuple[str, ...]: ...
    @property
    def mime_type(self) -> MimeType: ...
    @property
    def media_type(self) -> MediaType: ...
    def set_file_name(self, value: str) -> None: ...
    def set_stem(self, value: str) -> None: ...
    def set_extension(self, value: str) -> None: ...
    def set_extensions(self, values: Iterable[str]) -> None: ...
    def remove_extension(self) -> bool: ...
    def clear_extensions(self) -> bool: ...
    def set_mime_type(self, value: MimeType | str) -> None: ...
    def set_media_type(self, value: MediaType | MimeType | str) -> None: ...
    # A URL is a path with a scheme, so it answers under the `pathlib` names
    # the same questions a `PurePath` or a `Path` answers.
    @property
    def name(self) -> str: ...
    @property
    def suffix(self) -> str: ...
    @property
    def suffixes(self) -> tuple[str, ...]: ...
    @property
    def parts(self) -> tuple[str, ...]: ...
    @property
    def parent(self) -> Url: ...
    @property
    def parents(self) -> tuple[Url, ...]: ...
    def joinpath(self, *others: str | PathLike[str]) -> Url: ...
    def __truediv__(self, other: str | PathLike[str], /) -> Url: ...
    def with_name(self, value: str) -> Url: ...
    def with_stem(self, value: str) -> Url: ...
    def with_suffix(self, value: str) -> Url: ...
    def is_absolute(self) -> bool: ...
    def as_posix(self) -> str: ...
    def as_uri(self) -> str: ...
    def match(self, pattern: str) -> bool: ...
    def full_match(self, pattern: str) -> bool: ...
    def is_glob(self) -> bool: ...
    def relative_to(
        self, other: Url | Uri | Urn | str | PathLike[str]
    ) -> str: ...
    def is_relative_to(
        self, other: Url | Uri | Urn | str | PathLike[str]
    ) -> bool: ...
    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def is_private(self) -> bool: ...
    @property
    def partitions(self) -> tuple[tuple[str, str], ...]: ...
    def partition(self, column: str) -> str | None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, index: int, /) -> str: ...
    def __contains__(self, segment: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Url, /) -> bool: ...
    def __le__(self, other: Url, /) -> bool: ...
    def __gt__(self, other: Url, /) -> bool: ...
    def __ge__(self, other: Url, /) -> bool: ...
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> Url: ...
    def __deepcopy__(self, memo: Any) -> Url: ...

class Urn:
    def __init__(self, value: Urn | Uri | Url | str) -> None: ...
    @staticmethod
    def from_value(value: Urn | Uri | Url | str) -> Urn: ...
    @staticmethod
    def from_str(value: str) -> Urn: ...
    @staticmethod
    def from_uri(value: Uri) -> Urn: ...
    @staticmethod
    def from_json(value: str) -> Urn: ...
    def to_uri(self) -> Uri: ...
    def into_uri(self) -> Uri: ...
    def to_json(self) -> str: ...
    def into_json(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def authority(self) -> str: ...
    @property
    def path(self) -> str: ...
    @property
    def query(self) -> str | None: ...
    @property
    def fragment(self) -> str | None: ...
    @property
    def namespace(self) -> str: ...
    @property
    def namespace_specific(self) -> str: ...
    @property
    def path_segments(self) -> tuple[str, ...]: ...
    @property
    def file_name(self) -> str | None: ...
    @property
    def stem(self) -> str | None: ...
    @property
    def extension(self) -> str | None: ...
    @property
    def extensions(self) -> tuple[str, ...]: ...
    @property
    def mime_type(self) -> MimeType: ...
    @property
    def media_type(self) -> MediaType: ...
    def set_file_name(self, value: str) -> None: ...
    def set_stem(self, value: str) -> None: ...
    def set_extension(self, value: str) -> None: ...
    def set_extensions(self, values: Iterable[str]) -> None: ...
    def remove_extension(self) -> bool: ...
    def clear_extensions(self) -> bool: ...
    def set_mime_type(self, value: MimeType | str) -> None: ...
    def set_media_type(self, value: MediaType | MimeType | str) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...
    def __getitem__(self, index: int, /) -> str: ...
    def __contains__(self, segment: object, /) -> bool: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...
    def __lt__(self, other: Urn, /) -> bool: ...
    def __le__(self, other: Urn, /) -> bool: ...
    def __gt__(self, other: Urn, /) -> bool: ...
    def __ge__(self, other: Urn, /) -> bool: ...
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def __reduce__(self) -> tuple[object, tuple[str]]: ...
    def __copy__(self) -> Urn: ...
    def __deepcopy__(self, memo: Any) -> Urn: ...

class IOBase:
    def __init__(
        self, value: IOBase | Url | Uri | Urn | str | PathLike[str]
    ) -> None: ...
    @classmethod
    def from_bytes(
        cls, data: bytes | bytearray | memoryview | None = None
    ) -> IOBase: ...
    @property
    def url(self) -> Url | None: ...
    @property
    def name(self) -> str: ...
    @property
    def media_type(self) -> MediaType: ...
    @media_type.setter
    def media_type(self, media_type: MediaType | MimeType | str) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def parent(self) -> IOBase | None: ...
    @property
    def partitions(self) -> tuple[tuple[str, str], ...]: ...
    def joinpath(self, *others: str | PathLike[str]) -> IOBase: ...
    def __truediv__(self, other: str | PathLike[str], /) -> IOBase: ...
    def exists(self) -> bool: ...
    def is_dir(self) -> bool: ...
    def is_file(self) -> bool: ...
    def iterdir(self, include_private: bool = False) -> list[IOBase]: ...
    def ls(
        self, recursive: bool = False, include_private: bool = False
    ) -> list[IOBase]: ...
    def glob(
        self, pattern: str, include_private: bool = False
    ) -> list[IOBase]: ...
    def rglob(
        self, pattern: str, include_private: bool = False
    ) -> list[IOBase]: ...
    def children_where(
        self,
        filters: Mapping[str, str] | Iterable[tuple[str, str]],
        include_private: bool = False,
    ) -> list[IOBase]: ...
    def read_bytes(self) -> bytes: ...
    def read_text(self) -> str: ...
    # The write side takes `bytes` alone because the binding borrows the buffer
    # rather than copying it.
    def write_bytes(self, data: bytes) -> int: ...
    def write_text(self, text: str) -> int: ...
    def pread(self, offset: int, length: int) -> bytes: ...
    def pwrite(self, offset: int, data: bytes) -> int: ...
    def append(self, data: bytes) -> int: ...
    def mkdir(self) -> None: ...
    def touch(self) -> None: ...
    def unlink(self) -> None: ...
    def truncate(self, size: int) -> None: ...
    def flush(self) -> None: ...
    def open(self) -> None: ...
    def is_open(self) -> bool: ...
    def close(self) -> None: ...
    def __enter__(self) -> IOBase: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None = None,
        exception: BaseException | None = None,
        traceback: Any | None = None,
    ) -> bool: ...
    def copy_into(self, target: IOBase) -> int: ...
    def record_options(self) -> RecordOptions: ...
    def read_lines(self, pattern: str | None = None) -> LineIterator: ...
    def read_arrow_field(self, *, options: RecordOptionsLike | None = None) -> Field: ...
    def read_arrow_batch_reader(
        self, *, options: RecordOptionsLike | None = None
    ) -> pyarrow.RecordBatchReader: ...
    def write_arrow_batch_reader(
        self, batches: BatchesLike, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def append_arrow_batch_reader(
        self, batches: BatchesLike, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def read_arrow(
        self, *, options: RecordOptionsLike | None = None
    ) -> pyarrow.RecordBatchReader: ...
    def write_arrow(
        self, data: RowsLike, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def append_arrow(
        self, data: RowsLike, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def read_pandas(
        self, *, options: RecordOptionsLike | None = None
    ) -> Iterator[Any]: ...
    def read_pandas_frame(
        self, *, options: RecordOptionsLike | None = None
    ) -> Any: ...
    def write_pandas(
        self, frames: Any, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def write_pandas_frame(
        self, frame: Any, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def read_polars(
        self, *, options: RecordOptionsLike | None = None
    ) -> Iterator[Any]: ...
    def read_polars_frame(
        self, *, options: RecordOptionsLike | None = None
    ) -> Any: ...
    def write_polars(
        self, frames: Any, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def write_polars_frame(
        self, frame: Any, *, options: RecordOptionsLike | None = None
    ) -> None: ...
    def __fspath__(self) -> str: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[IOBase]: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...

# A root Field, however Python spells one: the native wrapper, a field
# expression, a PyArrow Schema, or a PyArrow Field.
FieldLike = Field | str | Any
# Anything that exports Arrow batches: a reader, a table, a batch, any Arrow C
# stream exporter, or a sequence of batches.
BatchesLike = Any
# Anything the generic entry points build a reader from: everything BatchesLike
# covers, plus a PyArrow Dataset or Scanner, a pandas or polars frame, an
# iterable of any of those, and an iterable of plain rows.
RowsLike = Any
# Record settings, or the media type naming the encoding they belong to.
RecordOptionsLike = RecordOptions | MediaType | MimeType | str

class RecordOptions:
    """The settings one record read or write takes."""

    def __init__(self, media_type: MediaType | MimeType | str) -> None: ...
    @classmethod
    def for_media_type(cls, media_type: MediaType | MimeType | str) -> RecordOptions: ...
    @property
    def mime_type(self) -> MimeType: ...
    @property
    def schema(self) -> Field | None: ...
    @schema.setter
    def schema(self, schema: FieldLike) -> None: ...
    @property
    def root_name(self) -> str: ...
    @root_name.setter
    def root_name(self, root_name: str) -> None: ...
    @property
    def safe(self) -> bool: ...
    @safe.setter
    def safe(self, safe: bool) -> None: ...
    @property
    def batch_size(self) -> int | None: ...
    @batch_size.setter
    def batch_size(self, batch_size: int | None) -> None: ...
    @property
    def level(self) -> int: ...
    @level.setter
    def level(self, level: int) -> None: ...
    @property
    def merge_by_names(self) -> list[str]: ...
    @merge_by_names.setter
    def merge_by_names(self, merge_by_names: Iterable[str]) -> None: ...
    @property
    def select_by_names(self) -> list[str]: ...
    @select_by_names.setter
    def select_by_names(self, select_by_names: Iterable[str]) -> None: ...
    @property
    def compression(self) -> str | None: ...
    @compression.setter
    def compression(self, compression: str) -> None: ...
    @property
    def max_row_group_size(self) -> int | None: ...
    @max_row_group_size.setter
    def max_row_group_size(self, rows: int) -> None: ...
    @property
    def key_value_metadata(self) -> dict[str, str] | None: ...
    @key_value_metadata.setter
    def key_value_metadata(
        self, metadata: Mapping[str, str] | Iterable[tuple[str, str]]
    ) -> None: ...
    def __repr__(self) -> str: ...

def assign_field_ids(schema: FieldLike, start: int = 1) -> Field: ...
def can_promote(
    from_type: DataType | str | Any, to_type: DataType | str | Any
) -> None: ...
def schema_from_json(name: str, document: Mapping[str, Any]) -> Field: ...
def schema_to_json(schema: FieldLike) -> dict[str, Any]: ...

class Catalog:
    """A warehouse folder of namespaces of Iceberg tables."""

    def __init__(self, warehouse: IOBase | Url | str | PathLike[str]) -> None: ...
    @property
    def warehouse(self) -> IOBase: ...
    def create_table(
        self, name: str, schema: FieldLike | Iterable[Field]
    ) -> Table: ...
    def table(self, name: str) -> Table: ...
    def has_table(self, name: str) -> bool: ...
    def open_or_create_table(
        self, name: str, schema: FieldLike | Iterable[Field]
    ) -> Table: ...
    def append(self, name: str, data: BatchesLike) -> Table: ...
    def overwrite(self, name: str, data: BatchesLike) -> Table: ...
    def list_namespaces(self, parent: str | None = None) -> list[str]: ...
    def list_tables(self, namespace: str) -> list[str]: ...
    def __repr__(self) -> str: ...

class Table:
    """An Iceberg table reached entirely through one container handle."""

    @classmethod
    def create(
        cls,
        root: IOBase,
        schema: FieldLike,
        partition_by: PartitionSpec | Iterable[str] | None = None,
        *,
        format_version: int | None = None,
    ) -> Table: ...
    @classmethod
    def open(cls, root: IOBase) -> Table: ...
    @classmethod
    def open_or_create(
        cls,
        root: IOBase,
        schema: FieldLike,
        partition_by: PartitionSpec | Iterable[str] | None = None,
        *,
        format_version: int | None = None,
    ) -> Table: ...
    @property
    def root(self) -> IOBase: ...
    @property
    def location(self) -> str: ...
    @property
    def format_version(self) -> int: ...
    @property
    def table_uuid(self) -> str: ...
    @property
    def version(self) -> int: ...
    @property
    def metadata_file_name(self) -> str: ...
    @property
    def metadata_location(self) -> str: ...
    @property
    def schema(self) -> Field: ...
    @property
    def spec(self) -> PartitionSpec: ...
    @property
    def current_snapshot(self) -> Snapshot | None: ...
    @property
    def snapshots(self) -> list[Snapshot]: ...
    @property
    def properties(self) -> dict[str, str]: ...
    @property
    def schemas(self) -> list[Field]: ...
    def manifests(self) -> list[ManifestFile]: ...
    def data_files(self) -> list[tuple[DataFile, PartitionSpec]]: ...
    def scan(self, field: FieldLike | None = None) -> pyarrow.RecordBatchReader: ...
    def scan_at(
        self,
        snapshot_id: int,
        filters: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
        schema: FieldLike | None = None,
    ) -> pyarrow.RecordBatchReader: ...
    def snapshot_by_ref(self, name: str) -> Snapshot: ...
    @property
    def target_file_size(self) -> int: ...
    def append(self, batches: BatchesLike) -> None: ...
    def overwrite(self, batches: BatchesLike) -> None: ...
    def evolve_schema(self, schema: FieldLike) -> int: ...
    def compact(self) -> Compaction: ...
    def inspect_history(self) -> pyarrow.RecordBatchReader: ...
    def inspect_snapshots(self) -> pyarrow.RecordBatchReader: ...
    def inspect_files(self) -> pyarrow.RecordBatchReader: ...
    def update_properties(
        self,
        updates: Mapping[str, str] | Iterable[tuple[str, str]] | None = None,
        removes: Iterable[str] | None = None,
    ) -> None: ...
    def update_schema(self) -> SchemaUpdate: ...
    def __repr__(self) -> str: ...

class SchemaUpdate:
    """A recorded set of column operations against one table's current schema."""

    def add_column(self, parent: str, field: Field | str | Any) -> SchemaUpdate: ...
    def drop_column(self, path: str) -> SchemaUpdate: ...
    def rename_column(self, path: str, name: str) -> SchemaUpdate: ...
    def update_doc(self, path: str, doc: str) -> SchemaUpdate: ...
    def make_nullable(self, path: str) -> SchemaUpdate: ...
    def update_type(
        self, path: str, data_type: DataType | str | Any
    ) -> SchemaUpdate: ...
    def commit(self) -> None: ...
    def __enter__(self) -> SchemaUpdate: ...
    def __exit__(
        self,
        exception_type: object = None,
        exception: object = None,
        traceback: object = None,
    ) -> bool: ...
    def __repr__(self) -> str: ...

class Compaction:
    """What one ``Table.compact`` call did, in numbers a caller can assert on."""

    @property
    def files_before(self) -> int: ...
    @property
    def files_after(self) -> int: ...
    @property
    def bytes_rewritten(self) -> int: ...
    def __repr__(self) -> str: ...

class PartitionField:
    """How a source column becomes a partition column."""

    @property
    def name(self) -> str: ...
    @property
    def transform(self) -> str: ...
    @property
    def source_id(self) -> int: ...
    @property
    def field_id(self) -> int: ...
    def __repr__(self) -> str: ...

class PartitionSpec:
    """The columns a table partitions on, in directory order."""

    @classmethod
    def unpartitioned(cls) -> PartitionSpec: ...
    @classmethod
    def identity(
        cls, schema: FieldLike, columns: Iterable[str], *, spec_id: int = 0
    ) -> PartitionSpec: ...
    @property
    def spec_id(self) -> int: ...
    @property
    def fields(self) -> list[PartitionField]: ...
    def is_unpartitioned(self) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class Snapshot:
    """One commit: what a table looked like at a point in time."""

    @property
    def snapshot_id(self) -> int: ...
    @property
    def parent_snapshot_id(self) -> int | None: ...
    @property
    def sequence_number(self) -> int | None: ...
    @property
    def timestamp_ms(self) -> int: ...
    @property
    def manifest_list(self) -> str: ...
    @property
    def operation(self) -> str: ...
    @property
    def schema_id(self) -> int | None: ...
    @property
    def summary(self) -> dict[str, str]: ...
    def __repr__(self) -> str: ...

class ManifestFile:
    """One manifest of a snapshot: which files it covers and what they hold."""

    @property
    def path(self) -> str: ...
    @property
    def length(self) -> int: ...
    @property
    def partition_spec_id(self) -> int: ...
    @property
    def sequence_number(self) -> int: ...
    @property
    def added_snapshot_id(self) -> int: ...
    @property
    def added_files_count(self) -> int: ...
    @property
    def existing_files_count(self) -> int: ...
    @property
    def deleted_files_count(self) -> int: ...
    @property
    def added_rows_count(self) -> int: ...
    @property
    def existing_rows_count(self) -> int: ...
    def is_data(self) -> bool: ...
    def __repr__(self) -> str: ...

class DataFile:
    """One data file a manifest lists."""

    @property
    def path(self) -> str: ...
    @property
    def file_format(self) -> str: ...
    @property
    def partition(self) -> tuple[Any, ...]: ...
    @property
    def record_count(self) -> int: ...
    @property
    def file_size_in_bytes(self) -> int: ...
    @property
    def value_counts(self) -> dict[int, int]: ...
    @property
    def null_value_counts(self) -> dict[int, int]: ...
    @property
    def column_sizes(self) -> dict[int, int]: ...
    @property
    def lower_bounds(self) -> dict[int, bytes]: ...
    @property
    def upper_bounds(self) -> dict[int, bytes]: ...
    @property
    def split_offsets(self) -> list[int]: ...
    @property
    def sort_order_id(self) -> int | None: ...
    @property
    def content(self) -> int: ...
    def __repr__(self) -> str: ...

class Timezone:
    """A canonical IANA time zone, with the offset rules this build knows."""

    UTC: ClassVar[Timezone]

    def __init__(self, value: str | Timezone | Any) -> None: ...
    @classmethod
    def from_value(cls, value: str | Timezone | Any) -> Timezone: ...
    @classmethod
    def from_offset(cls, seconds: int) -> Timezone: ...
    @classmethod
    def registered(cls) -> tuple[Timezone, ...]: ...
    @classmethod
    def aliases(cls) -> tuple[tuple[str, str], ...]: ...
    @property
    def key(self) -> str: ...
    @property
    def standard_offset(self) -> int | None: ...
    def is_utc(self) -> bool: ...
    def is_known(self) -> bool: ...
    def is_fixed(self) -> bool: ...
    def observes_saving(self) -> bool: ...
    def offset_at(self, epoch: int) -> int | None: ...
    def is_saving_at(self, epoch: int) -> bool | None: ...
    def abbreviation_at(self, epoch: int) -> str | None: ...
    def to_local(self, epoch: int) -> int: ...
    def to_utc(self, local: int) -> int: ...
    def utcoffset(self, epoch: int = 0) -> Any | None: ...
    def stable_hash(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...
    def __copy__(self) -> Timezone: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Timezone: ...

class LineIterator:
    """Iterator over a resource's decoded text lines, one line at a time."""

    def __iter__(self) -> LineIterator: ...
    def __next__(self) -> str: ...

def gzip_loads(data: bytes) -> bytes: ...
def gzip_dumps(data: bytes, level: int | None = None) -> bytes: ...
def zlib_loads(data: bytes) -> bytes: ...
def zlib_dumps(data: bytes, level: int | None = None) -> bytes: ...
def zstd_loads(data: bytes) -> bytes: ...
def zstd_dumps(data: bytes, level: int | None = None) -> bytes: ...
