"""Mypy support for methods installed by :func:`yggdryl.scalar`."""

from __future__ import annotations

from collections.abc import Callable

from mypy.plugin import ClassDefContext, Plugin
from mypy.plugins.common import add_method_to_class
from mypy.types import LiteralType

_SCALAR_DECORATORS = {
    "yggdryl.scalar",
    "yggdryl.scalar.scalar",
}


def _add_field_accessor(context: ClassDefContext) -> None:
    """Teach mypy about the cached staticmethod installed at runtime."""

    string_type = context.api.named_type("builtins.str")
    struct_field = context.api.named_type(
        "yggdryl.fields._typing.TypedField",
        [
            LiteralType("struct", string_type),
            context.api.named_type("builtins.object"),
        ],
    )
    add_method_to_class(
        context.api,
        context.cls,
        "field",
        args=[],
        return_type=struct_field,
        is_staticmethod=True,
    )


class YggdrylPlugin(Plugin):
    """Describe members generated by Yggdryl's Python decorators."""

    def get_class_decorator_hook(
        self, fullname: str
    ) -> Callable[[ClassDefContext], None] | None:
        if fullname in _SCALAR_DECORATORS:
            return _add_field_accessor
        return None


def plugin(version: str) -> type[YggdrylPlugin]:
    """Return the plugin entry point expected by mypy."""

    return YggdrylPlugin
